### ISSUE TITLE
Nuget, OK, NPM better

### ISSUE THREAD

**Issue by Net-IT-Jonathan** [delegateas/XrmDefinitelyTyped#100]
Why is't there a release on NPM? It's easier for folder based projects in Visual Studio Code.

**Comment by magesoe** [comment]
We never made a NPM package because you are the first to ask for it :). I guess you just want the executable and its dependencies in the package?

**Comment by Net-IT-Jonathan** [comment]
> We never made a NPM package because you are the first to ask for it :). I guess you just want the executable and its dependencies in the package?

I would like to use your framework in a Visual Studio Code project. So, no VS project or solution files. This is going to very useful once the PCF comes out, not like this morning, it was a false start...

**Comment by magesoe** [comment]
But do you actually want a .exe file in your node_modules?

**Comment by mdocter** [comment]
> But do you actually want a .exe file in your node_modules?

Yes, that's very common. The `Yarn` package manager can for example run executables via `yarn run [name of exe]` from the `./node_modules/.bin` folder. `npm` can do something similar.

**Comment by magesoe** [comment]
I have added XDT as an npm package @delegateas/xrmdefinitelytyped

Can you verify that it is what you expected?

**Comment by mdocter** [comment]
Thanks! That's great @magesoe.
Can you also add the `./node_modules/.bin` files? See [https://yarnpkg.com/en/docs/package-json#bin-](https://yarnpkg.com/en/docs/package-json#bin-)

**Comment by magesoe** [comment]
shouldn't everything be in the .bin directory then?

**Comment by mdocter** [comment]
I think so, when looking at the docs. I never did it myself, so I am not a great help here.

**Comment by fowl2** [comment]
It seems that there now is a [package](https://www.npmjs.com/package/@delegateas/xrmdefinitelytyped)!

Last updated 2 years ago, but #178 is there to fix that.

**Comment by misoeli** [comment]
While there's an issue with the npm package for now, there's another issue for looking into that (#178 ). Closing here.
