### ISSUE TITLE
Releases in NuGet can't be found in release branches

### ISSUE THREAD

**Issue by Net-IT-Jonathan** [delegateas/XrmDefinitelyTyped#101]
For obvious reasons, add Release Branches to every release please.

**Comment by magesoe** [comment]
We could do that, but what exactly are the obvious reasons? Don't you get the desired effect from what we do now where we write "published nuget x.x.x" in a commit?

**Comment by Net-IT-Jonathan** [comment]
> We could do that, but what exactly are the obvious reasons? Don't you get the desired effect from what we do now where we write "published nuget x.x.x" in a commit?

It's easier to see what is happening if you can check the actual code. Now, you have to upgrade for that and in close-to-production projects upgrades of Nugets is not recommended.

**Comment by magesoe** [comment]
But why do you need a branch? We write a commit for each release. You can checkout a branch as well as a commit, is it because it's easier to checkout a branch?

**Comment by misoeli** [comment]
Closing. Please reach out if the above need is still relevant, but please consider magesoe's comment first.
