### ISSUE TITLE
The security token could not be authenticated or authorized

### ISSUE THREAD

**Issue by altmank** [delegateas/XrmDefinitelyTyped#102]
Hello,

Trying to get this tool to work on an on-prem instance of Dynamics (8.2) IFD enabled and I always get the error "The security token could not be authenticated or authorized". Looking at Fiddler recordings, it looks like it tries to get the WSDL and is then directed to our ADFS instance to authenticate, eventually failing with the above error in the response from ADFS. Not sure what is different about how this program tries to authenticate via ADFS versus other Dynamics tools that work without issue.

https://i.imgur.com/Nporiwz.png
https://i.imgur.com/6TaypON.png

Any suggestions?

**Comment by magesoe** [comment]
Could you show the settings you're calling XrmDefinitelyTyped with? You might be using the wrong authentication provider.

**Comment by altmank** [comment]
Here is the XrmDefinitelyTyped.exe.config file, minus some personal details:

https://i.imgur.com/Ijgdq2O.png

**Comment by henrikhannemose** [comment]
We have the [possibility of specifying the AuthenticationProvider](https://github.com/delegateas/XrmDefinitelyTyped/wiki/Tool-usage#arguments) to use when running XrmDefinitelyTyped. If none is specified, the tool falls back to using OnlineFederation.

Could you try adding the following line to your XrmDefinitelyTyped.exe.config?
`<add key="ap" value="Federation" />`

We should probably add this key to the default .config (just like we have in Daxif). Any objections, @magesoe?

**Comment by altmank** [comment]
@henrikhannemose I added that to the config and I observed no change in the issue.

**Comment by altmank** [comment]
Made some progress here, I updated the username key in the config to prefix my username with the domain for the user. This allowed me to get past the first error. But I'm still getting an authentication error after that. The new authentication error now happens when the tool is performing the "Retrieving CRM Version..." step. Looking at Fidder, the failure happens in the RetrieveVersion request. The response from the server is "Access is Denied". It is not clear why the tool can now successfully connect to the instance and retrieve the WSDL but then fails on an execute RetrieveVersion request.

Any suggestions here? Is there another authentication type I can try?

**Comment by magesoe** [comment]
Is the user system administrator?

**Comment by altmank** [comment]
Yes.

**Comment by altmank** [comment]
Okay. I found a resolution. For our DEV system, we have two URLs. I don't know the exact configuration in ADFS but logging in from a browser one of the URLs is supposed to authenticate using your existing AD account logged into your computer, while the other prompts a login screen where you have to manually enter your AD credentials. 

The URL I was attempting to use with this tool was the one that should authenticate with existing AD account logged into your computer. Once I switched to the second type AND prefixed the domain to the username, I was able to get it to work. 

If I tried to use the config setting "domain" instead of putting the domain in the username field before the username, I ended up with the same authentication issue that I first mentioned in this issue. So for whatever reason I can't use the domain setting in our configuration with this tool.

Sorry I don't have more specifics on the exact ADFS config differences between to two URLs to perhaps enable you to better understand.

**Comment by magesoe** [comment]
It's okay, just glad you got it working!
