### ISSUE TITLE
Promise.all() not working with XrmQuery.promise()

### ISSUE THREAD

**Issue by siggimar92** [delegateas/XrmDefinitelyTyped#103]
Hi, 
I was wondering if there is an alternative to Promise.all or if you know how it's possible to use it with the library?

![image](https://user-images.githubusercontent.com/5701803/56291884-9eec3b00-6115-11e9-89df-c58313418ead.png)

**Comment by magesoe** [comment]
The following builds for me, haven't tested if it works, but I assume it does. 
I think you just need to wrap it in an await, so if you put await before your Promise.all then it will work.
```typescript
let bla = await Promise.all([
      XrmQuery.retrieveMultiple(x => x.accounts).promise(),
      XrmQuery.retrieveMultiple(x => x.contacts).promise()
    ])
```

**Comment by siggimar92** [comment]
Hmmm ok, I still seem to get an error:
![image](https://user-images.githubusercontent.com/5701803/56472003-cd855100-6448-11e9-8e61-461d403a4662.png)
How is your tsconfig file?

**Comment by magesoe** [comment]
Referenced my tsconfig here https://github.com/delegateas/XrmDefinitelyTyped/issues/104#issuecomment-484133429

**Comment by siggimar92** [comment]
Thank you for a fast reply!
I had to install this library: es6-promise.TypeScript.DefinitelyTyped
Then it worked :)

**Comment by obkirneh** [comment]
Hi @siggimar92,

I've been playing around with promises as well and the only typings I have is the ones generated by XrmDefinitelyTyped.
My **tsconfig.json** looks like this:

> {
  "compileOnSave": true,
  "compilerOptions": {
    "outDir": "js",
    "sourceMap": true,
    "removeComments": true,
    "target": "es5",
    "lib": ["es2015", "dom"]
  }
}

**es2015** & **dom** did the trick

Check out [issue 36](https://github.com/delegateas/XrmDefinitelyTyped/issues/36)
