### ISSUE TITLE
Intial Setup Errors xrm.d.ts

### ISSUE THREAD

**Issue by MickEtcha** [delegateas/XrmDefinitelyTyped#104]
Hi,

I'm setting up an a project for the first time using your tool with the following settings.

XrmDefinitelyTyped v 4.3.1
D365 v 9.0.2.3

I'm getting the following errors in the xrm.d.ts 

![image](https://user-images.githubusercontent.com/6329519/56295274-6d2ea080-6124-11e9-9e19-1940928c3063.png)

I've made the following changes to the tsconfig file.

```
"include": [
    "ts/**/*",
    "src/**/*",
    "typings/**/*"
  ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts"
  ]
```

Could you advise if this is a configuration issue on my part. My colleague tried the same steps with v8.2 and was successful.

Thank you in advance,
Mick

**Comment by magesoe** [comment]
I don't have a problem with 4.3.1, but I do use version 9.1. That said, I also tried generating for your version of CRM using the `cv` argument, where you can specify a version. It also worked just fine there.

I have the following .tsconfig file, but I can't see any reason why yours would fail. Perhaps you can seek inspiration in our project setup https://github.com/delegateas/XrmFramework
```json
{
    "compileOnSave": true,
    "compilerOptions": {
        "target": "es5",
        "noImplicitAny": false,
        "module": "none",
        "removeComments": true,
        "declaration": false,
        "sourceMap": true,
        "noEmitOnError": false,
        "strictNullChecks": true,
        "lib": [ "dom", "es5", "es2015.promise" ]
    },
    "filesGlob": [
        "**/*.ts"
    ]
}
```

**Comment by MickEtcha** [comment]
@magesoe thank you for the response.

By `cv` you mean the `crmVersion` arguement?

I've added this and used your tsconfig and I've successfully built the project. I'll reference the XrmFramework page in the future.

Thanks for the prompt response,
Mick

**Comment by magesoe** [comment]
Yes, both the long and short version can be used. Try and remove it, it uses the version of the XRM SDK you use it with.

Don't know why you .tsconfig doesn't work though. And if it does and it was actually fixed by adding the version, then check the version of your SDK, it might be old
