### ISSUE TITLE
type Xrm.EntityReference<"systemuser"> cannot be generated in JS

### ISSUE THREAD

**Issue by charliechen179** [delegateas/XrmDefinitelyTyped#106]
Hi there,

I have a ts function to populate the value of system user for a lookup like below. Unfortunately, when I compile it into JS and deploy it to D365. I get the error: landingUser is undefined.  I guess the library xrm.d.ts cannot be referenced by JS file in runtime and I don't find a way to generate the same file into JS folder. Does anybody have any idea? Thanks!

**ts:**
export function onChange(executionContext: Xrm.ExecutionContext<any>) {
        Form = <Form.sl_extensionrequest.Main.Information>executionContext.getFormContext();
        let landingUser: Xrm.EntityReference<"systemuser">[];
        landingUser[0].id = Xrm.Utility.getGlobalContext().userSettings.userId;
        landingUser[1].id = Xrm.Utility.getGlobalContext().userSettings.userName;
        Form.getAttribute("ownerid").setValue();
        Form.getAttribute("sl_approvedon").setValue(new Date);
    }

**JS**
function onChange(executionContext) {
                    Form = executionContext.getFormContext();
                     var landingUser;
                    landingUser[0].id = Xrm.Utility.getGlobalContext().userSettings.userId;
                    landingUser[1].id = Xrm.Utility.getGlobalContext().userSettings.userName;
                    Form.getAttribute("ownerid").setValue();
                    Form.getAttribute("sl_approvedon").setValue(new Date);
                }

**Comment by magesoe** [comment]
You forced the type of landingUser to be Xrm.EntityReference<"systemuser">[], but you never gave it a value, you just declared it. There are other errors in your example, but that is the cause of your error.

Whenever you work with entity references, I suggest you do it like the example below, and not the way you attempted it here. 
```typescript
Form.getAttribute("pricelist").setValue([{
      entityType: "pricelevel",
      id: billing.dg_pricelist_guid,
      name: billing.dg_pricelist_formatted
    }])
```

I notice that you're trying to work with owner. The Web API requires that you use the associate request whenever you try to set the owner. XrmQuery also supports this with `XrmQuery.associateSingle(...)`

**Comment by charliechen179** [comment]
Thanks a lot for your reply!

![image](https://user-images.githubusercontent.com/29467948/56804693-a20db800-67f4-11e9-8ae2-010b7297bd10.png)
The reason I forced it to Xrm.EntityReference<"systemuser">, is because setValue() method ask for it. After I forced it, I actually get intellisense as below.

![image](https://user-images.githubusercontent.com/29467948/56804879-35df8400-67f5-11e9-9398-4d1d831d2983.png)


 I want to use the strong type benefit like c#. Therefore I think xrm.d.ts should have an equivalent JS.

**Comment by magesoe** [comment]
Typescript has even stronger type benefits than C#, so you've come to the right place.

The JS that is generated exactly matches your Typescript.

You wrote
```typescript
let landingUser: Xrm.EntityReference<"systemuser">[];
```
Instead of
```typescript
let landingUser: Xrm.EntityReference<"systemuser">[] = [{
    entityType: "systemuser", 
    id: "",
    name: "Bill Bob"
}];
```
You never assigned a value to landingUser, therefore the generated JS doesn't assign a value either

**Comment by charliechen179** [comment]
Yes, you're right. I wish I can use a list here.

**Comment by charliechen179** [comment]
Thanks @magesoe for letting me know how to use IntelliSense with XrmDefinitelyTyped.
