### ISSUE TITLE
XQW.stripGuid broken in version 4.3.1

### ISSUE THREAD

**Issue by strwase** [delegateas/XrmDefinitelyTyped#108]
XQW.stripGuid doesn't clear the parentheses from a guid field.
the endswith part of the function returns false when it should return true.
making the function just return the original string instead of the stripped version.

![image](https://user-images.githubusercontent.com/10077785/57450894-04889e80-7260-11e9-9383-3cb7d66f9eea.png)

**Comment by altmank** [comment]
I think that is caused by this commit:
https://github.com/delegateas/XrmDefinitelyTyped/commit/495f54e00bf8542fe46ce9d372bdf8ea44426ea4#r33534979

**Comment by magesoe** [comment]
Fixed in version 4.3.2
