### ISSUE TITLE
xrmQueryToCrm should check for _guid at the end of the attribute name

### ISSUE THREAD

**Issue by mdocter** [delegateas/XrmDefinitelyTyped#111]
I noticed that when I created a XrmQuery containing an attribute name like `new_guids` broke the OData query string. 
The getQueryString() function doesn't return `...$select=new_guids`, but `...$select=_new_value`. The attribute name was cut off from the start of `_guid`. This should only be done in case of an attribute name that ends with '_guid', not when it's somewhere in the middle.
I will create a pull request to fix this issue.

**Comment by mdocter** [comment]
Thanks @magesoe!

**Comment by magesoe** [comment]
Thanks for fixing it! It has been added in version 4.3.5.

There is still a problem with this approach though. It is possible to create attributes called `new_xxx_guid`. But after a quick coffee discussion at Delegate we agreed that if you do that it's your own fault and you should be ashamed :)

**Comment by magesoe** [comment]
The proper way to check this is to look at the metadata, but until this problem becomes urgent I think your solution is acceptable

**Comment by mdocter** [comment]
I absolutely agree. Thanks for merging the PR and the great library. 
Any news on my other open issue #107?

**Comment by magesoe** [comment]
Haven't gotten to it yet. We have been busy lately, as is clear from the speed that we answer and fix issues. But we can't complain, we love that others use it and catch errors for us

**Comment by mdocter** [comment]
I understand. Keep up the good work!
