### ISSUE TITLE
Remove Connection settings from Config file

### ISSUE THREAD

**Issue by namurdock** [delegateas/XrmDefinitelyTyped#114]
Firstly,  thank you to all contributors on this project, it is truly amazing and a massive time saver. (once i remove my education in the ways of typescript).

As we source control all our projects it would be great if the xrmtooling command line interface could be used instead of storing credentials in the config file.

If there are alternative ways of storing credentials that i have missed in the documentation then apologies.

**Comment by henrikhannemose** [comment]
Thanks for using XrmDefinitelyTyped :)

I know it is not documented too well, but we do not ourselves use the .config file for XrmDefinitelyTyped. Instead we run XrmDefinitelyTyped (and our other tools) through the tool called [DAXIF](https://github.com/delegateas/Daxif).
DAXIF has a single config-file (`_Config.fsx`) that can be used across different tools (in this way you don't have to maintain separate config files for each tool).

You specify your environment in the [ _Config.fsx](https://github.com/delegateas/Daxif/wiki/_Config) file as follows:
```
module Env =
  let dev = 
    Environment.Create(
      name = "Development",
      url = "https://mydev.crm4.dynamics.com/XRMServices/2011/Organization.svc",
      ap = AuthenticationProviderType.OnlineFederation,
      creds = creds,
      args = fsi.CommandLineArgs
    )
```

Credentials are stored in separate `.daxif` files. In this way you can easily keep credentials out of source control, and each developer instead store their own credentials in an encrypted file on their local machine. The first time the user runs the tool, they will be prompted for credentials (which are then stored in a local `.daxif` file).

I thus suggest that you download the latest DAXIF nuget package, and run the [`GenerateTypescriptContext.fsx`](https://github.com/delegateas/Daxif/wiki/GenerateTypescriptContext) script after setting up your environment in `_Config.fsx`. This will execute XrmDefinitelyTyped without using its .config file.

**Comment by henrikhannemose** [comment]
Did you manage to move forward with using DAXIF?
Otherwise you can also run the XrmDefinitelyTyped executable without using the config-file by specifying your arguments at run time. An example of this can be seen in [Command Prompt](https://github.com/delegateas/XrmDefinitelyTyped/wiki/Tool-usage#command-prompt).

**Comment by namurdock** [comment]
Nice. Thanks for the tip. Sorry I've not got round to looking into it yet.

Thanks for the pointer though I'll definitely check it out.

**Comment by magesoe** [comment]
Any update on this issue?

**Comment by LycraLout** [comment]
FWIW, we put the connection settings into arguments in run.ps1 with uc:true and gitignore that file. That way we can commit the config file and everyone is up to date but keeping creds secret. Prior to doing that we were ignoring the config file and had a situation where a lot of typings were lost when the team weren't told to update the entities list.

**Comment by FixRM** [comment]
Thy not to use sdk's sample to work with connections? It securely store secrets in windows key vault and have interactive command line experience.

**Comment by ferodom** [comment]
Have you guys been using the client secret in DaxIf, I would like to be able to store the client secret in a daxif file. If you could point me in the right direction that would be awesome

**Comment by magesoe** [comment]
> Have you guys been using the client secret in DaxIf, I would like to be able to store the client secret in a daxif file. If you could point me in the right direction that would be awesome

I only use the client secret authentication from the build pipeline, which passes the authentication as a parameter. Locally I use OAuth, since I don't want to generate secrets for every developer

**Comment by annesofienoerager** [comment]
The documentation has been updated, and is now covering how to sign in using OAuth and thereby removing your password from the config file. See more under "Getting started".
