### ISSUE TITLE
Missing getCurrentAppUrl() method from Global Context xrm.d.ts template

### ISSUE THREAD

**Issue by DavidPezzoli** [delegateas/XrmDefinitelyTyped#119]
Hi,
Into xrm.d.ts template there isn't the method of Global Context: getCurrentAppUrl()
this method is important in order to detect if the user is in the new user interface:
https://stackoverflow.com/questions/54030051/how-to-determine-if-dynamics-xrm-javascript-is-being-invoked-from-the-unified-in

you can see:
function isUCI() {
   var globalContext = Xrm.Utility.getGlobalContext();
   var t1 = globalContext.getCurrentAppUrl();
   var t2 = globalContext.getClientUrl();
   return t1 !== t2;
}

Regards,

**Comment by magesoe** [comment]
Added in 4.3.12
