### ISSUE TITLE
Getting error when attribute name is not specified

### ISSUE THREAD

**Issue by charliechen179** [delegateas/XrmDefinitelyTyped#122]
I try to set value for one of date fields on form which is unknown at design time, but I got an error as shown below and can compile the ts file. If I specified which date field to set, the code is good. Please help.

![image](https://user-images.githubusercontent.com/29467948/60559081-6540ce80-9d19-11e9-978b-e1ff91a8a5e7.png)

**Comment by henrikhannemose** [comment]
The general approach to re-use code is not to have the name of the attribute as a parameter. Instead, have the actual attribute/control as a parameter.

You can see how we suggest re-using code [in this reply](https://github.com/delegateas/XrmDefinitelyTyped/issues/81#issuecomment-436797137). In your case it would look something like this:
```typescript
setDateAndApprover(Form.getAttribute("my_dateattribute1"));
setDateAndApprover(Form.getAttribute("my_dateattribute2"));

function setDateAndApprover(attr: Xrm.DateAttribute) {
  attr.setValue(new Date());
}
```

You might want to consider whether the actual use case of setting the approval date client side is something you want to do, or if that is actually better suited for server side code. I'll leave that up to you.

**Comment by charliechen179** [comment]
Great! That's exactly what I want. I tried to find any similar issue, but I didn't go through the content on that reply. Thank you very much. @henrikhannemose

**Comment by TomMalow** [comment]
I'm closing this issue as it seems like you got your answer
