### ISSUE TITLE
form.data.process.getStatus(); not supported

### ISSUE THREAD

**Issue by ntinggaard** [delegateas/XrmDefinitelyTyped#131]
Looks like Microsoft has changed the method used to retrieve status of BPF.
According to MS documentation the following method is to be used, which is not supported by XrmDefinitelyTyped: formContext.data.process.getStatus();

https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-data-process/instance/getstatus

**Comment by magesoe** [comment]
I added the additional new methods from that page. Looks like they just added a short-hand, since you previously had to get the process instance. Added in version 4.3.14
