### ISSUE TITLE
Generated formfiles broken since upgrade to crm9

### ISSUE THREAD

**Issue by Flydancer** [delegateas/XrmDefinitelyTyped#133]
We've updated our CRM to v9 recently. 
When I run XrmDefinitelyTyped now it modifies my formfiles (e.g "Informationen.d.ts") to a nearly empty file and creates a new formfile "Informationen1.d.ts" which is the correct one.

Why is this happening? Before the CRM update it just updated the existing files, now it breaks my whole project.

Thanks in advance,
Alex

**Comment by magesoe** [comment]
Can you show us how you call XDT? All my customers run XDT with the latest CRM version

**Comment by Flydancer** [comment]
I guess I've found the issue:
There is also a deactivated form with the same name and it looks like deactivated forms have been ignored before v9 (v8.2). 
There is no setting to tell XDT to ignore deactivated forms, right?

**Comment by magesoe** [comment]
There is, skipInactiveForms. You can see it on the wiki https://github.com/delegateas/XrmDefinitelyTyped/wiki/Tool-usage

**Comment by Flydancer** [comment]
Hi magesoe,
when I try to add <add key="sif" value="true"/> (or skipInactiveForms) to the config
it tells me Option 'sif' not recognized. when running.
Do you have an Idea whats wrong?

**Comment by magesoe** [comment]
Did you manage to fix it?

**Comment by Flydancer** [comment]
Hello Magnus,
yes, after updating XDT to a newer version because mine didn't recognize the sif flag.
Thanks a lot.
