### ISSUE TITLE
One d.ts file with all enums -- simplify testing

### ISSUE THREAD

**Issue by skfd** [delegateas/XrmDefinitelyTyped#138]
**Is your feature request related to a problem? Please describe.**
To do testing I need to reference each individual Enum defined in `_internal/Enum` directory. It gets somewhat tedious because Typescript does not support wildcards in references:
```
/// <reference path="../../definitions\typings\XRM\_internal\Enum\*.d.ts" /> //<-- not supported
```

**Describe the solution you'd like**
It would e cool to make a file `Enums.d.ts` that references all files or has all the enum definitions.

**Describe alternatives you've considered**
Right now I have to go to the top of the file and reference individual `d.ts` files. It works ok.

**Comment by magesoe** [comment]
Isn't this already solved by the onefile setting?
