### ISSUE TITLE
Typings for Dialogs (Xrm.Navigation)

### ISSUE THREAD

**Issue by mlRosenquist** [delegateas/XrmDefinitelyTyped#142]
**Is your feature request related to a problem? Please describe.**
It's not possible to set the title on an alertDialog, even though it's supported in the Xrm.Navigation documentation: 

[https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-navigation/openalertdialog](url)

**Describe the solution you'd like**
Seems XDT is outdated and requires an update.

**Comment by magesoe** [comment]
Added in 4.4.3
