### ISSUE TITLE
New text field writes 'Single-Line_of text' in Entity.d.ts when add in form, after Wave 2

### ISSUE THREAD

**Issue by joelnetodev** [delegateas/XrmDefinitelyTyped#144]
I have renamed the **Account** entity to **Compay** an created a Auto-Number field, called Company ID and add to the **Main Form** as **Lock** and **Read-Only**. I was using the new interface to do it in [make.powerapps.com](make.powerapps.com). And I noticed in the **Company.d.ts**, in the Main Form folder, inside **ControlMap** interface, the **Single-Line_of Text: Control.String** was being written instead of field name, after connection and creation of the files.

For some reason this name was following the my **Chrome language settings**. I changed the language on Chrome and put in **Portuguese**, then I did the process again, created the Auto-Number field and put in the form. The same issue was happening, but instead of Single-Line_of Text I was having **Unica-Linda_de texto**. This started to happens **these days, on [make.powerapps.com](make.powerapps.com), after Wave 2**. I dont know if CRM is putting wrong Ids or Changed the Ids in the new form customization page.

PS: **< add key="gm" value="true" />**  was add to the config.

**Comment by misoeli** [comment]
Not something I can reproduce. My best guess is it might have been a temporary issue related to wave release. Please reopen if the issue still applies.
