### ISSUE TITLE
Cannot run build script with combination of Gulp 3 and Node 12

### ISSUE THREAD

**Issue by TomMalow** [delegateas/XrmDefinitelyTyped#145]
**Describe the bug**
There is a an issue with running the build script when using latest version of Node.

**To Reproduce**
1. install node v12+
2. execute build.cmd

**Additional context**
The issue is mentioned here https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node
The solution is to upgrade gulp to version 4.x

**Comment by magesoe** [comment]
Fixed in 81c4f870d5f77a1fdde683faee262173834e75e3
