### ISSUE TITLE
Access is denied.

### ISSUE THREAD

**Issue by pagex** [delegateas/XrmDefinitelyTyped#148]
On prem CRM 2016 8.2, Windows Authentication, Retrieving CRM version... then Unable to generate TypeScript files: Access is denied.  Note credentials I've put are correct, if I deliberately put wrong ones, it comes with "Caller was not authenticated by service" my config:
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>
    <add key="url" value="http://xxxx/XRMServices/2011/Organization.svc" />
    <add key="username" value="xxxxx" />
    <add key="domain" value="test" />
    <add key="password" value="xxxxx" />
    <add key="out" value="../typings" />
    <add key="solutions" value="" />
    <add key="entities" value="account, contact" />
    <add key="web" value="" />
    <add key="jsLib" value="../src/lib" />
    <add key="ap" value="ActiveDirectory" />
    
  </appSettings>
</configuration>

**Comment by pagex** [comment]
Closing this off as we used non default ORG so URL has to include Org name instead of default.
http://xyz/orgname/XRMServices/2011/Organization.svc

**Comment by TomMalow** [comment]
This good to know. In the recent years we have moved more towards online so we don't have that many on-prem to test these issues on.
