### ISSUE TITLE
Handle deprecations in client APIs in D365 9.0

### ISSUE THREAD

**Issue by henrikhannemose** [delegateas/XrmDefinitelyTyped#15]
With the July 2017 update for Dynamics 365 [some client APIs are deprecated](https://docs.microsoft.com/en-us/dynamics365/get-started/whats-new/customer-engagement/important-changes-coming#some-client-apis-are-deprecated). They are currently still available, but will be removed in a future version. A list of replacement functions are available at the above link.

Additionally, [new client APIs](https://docs.microsoft.com/en-us/dynamics365/get-started/whats-new/customer-engagement/new-in-july-2017-update-for-developers#new-client-apis) have been introduced.

**Comment by Tolini** [comment]
[According to microsoft](https://blogs.msdn.microsoft.com/crm/2017/10/16/just-released-new-and-updated-content-for-the-july-2017-update-for-dynamics-365-online/) they will release documentation for 9.0 within this month. Once released we will implement the remaining of the deprecated features as well as the new features that it brings.

**Comment by henrikhannemose** [comment]
Microsoft have now released the documentation (and even dated it 31st of October...): https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/clientapi/reference

**Comment by henrikhannemose** [comment]
Have all these deprecations been implemented, such that we can close this issue @Tolini?

**Comment by Tolini** [comment]
Everything except for quick view forms. But those aren't implemented for earlier versions of CRM either.
