### ISSUE TITLE
Grid Control: new methods

### ISSUE THREAD

**Issue by mathiasbl** [delegateas/XrmDefinitelyTyped#154]
https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/grids/gridcontrol

Added methods:
- getFetchXml
- getRelationship
- getGridType
- getUrl
- openRelatedGrid
- refreshRibbon

Removed methods:
- getRelationshipName

I would make a PR but I'm a bit confused on where to add it with these xrm_ext_{v}- and xrm_ext_-{v} files . If you can give me some guidance I can go ahead and make it.

**Comment by magesoe** [comment]
The idea is to capture when it was added, deprecated and removed.
The version is x-y-z if it was
Added in x
Deprecated in y
Removed in z

Thank you for all your PR's!

**Comment by mathiasbl** [comment]
PR made. I hope I did everything correct. :)

**Comment by magesoe** [comment]
Was added in 4.4.6
