### ISSUE TITLE
Form programming methods introduced in CRM 2013 should not appear when using CRM 2011

### ISSUE THREAD

**Issue by lisbyschmidt** [delegateas/XrmDefinitelyTyped#16]
The new form programming methods available in Microsoft Dynamics CRM 2013 are documented here:
https://msdn.microsoft.com/en-us/library/gg328261(v=crm.6).aspx#BKMK_NewFormAPIs

I would like them to be omitted when generating typings in Microsoft Dynamics CRM 2011.

**Comment by magesoe** [comment]
Fixed in 2.3.1

**Comment by lisbyschmidt** [comment]
Thanks for working on this issue. :)

However, there seems to be a bug in version 2.3.1. When generating new typings the "client" interface below is no longer part of xrm.d.ts. This is fine except that it is still referenced in the "context" interface in xrm.d.ts, which means that my build fails. If I manually remove this reference, everything builds just fine.

    interface client {
        /**
         * Returns a value to indicate which client the script is executing in.
         */
        getClient(): ClientType;

        /**
         * Use this instead of the removed isOutlookOnline method.
         */
        getClientState(): ClientState;
    }


    interface context {
        /**
         * Provides access to the getClient and getClientState methods you can use to determine which client is being used and whether the client is connected to the server.
         */
        client: client; // Please remove this

        // Rest of interface omitted...
    }

**Comment by magesoe** [comment]
Thanks for noticing! It has now been removed and builds just fine on our test environment

**Comment by lisbyschmidt** [comment]
It's me again. :) Your last change fixed the problem.

However, I have come across more methods that isn't available in CRM 2011. Maybe that is considered a separate issue, but here goes.

Introduced in CRM 2013:
Xrm.Utility.isActivityType
Xrm.Page.context.getUserName
Lookup: Xrm.Page.getControl(arg).addPreSearch
Lookup: Xrm.Page.getControl(arg).removePreSearch
"then" method (interface Then) only makes sense after async refresh or save.

Introduced in CRM 2015:
Xrm.Utility.openQuickCreate
Xrm.Page.context.getIsAutoSaveEnabled
Xrm.Page.context.getTimeZoneOffsetMinutes
DateTime: Xrm.Page.getControl(arg).getShowTime
Subgrid: Xrm.Page.getControl(arg).getRelationshipName
Xrm.Page.ui.process.xyz and Xrm.Page.data.process.xyz only makes sense with business process flows. It seems that interfaces with names containing "process" or "stage" are not needed in CRM 2011. And possibly "interface DataModule".

Bugs:
- My generated file is missing a semicolon in "interface SubGridControl". I get "getRelationshipName(): string" instead of "getRelationshipName(): string;".
- I believe the method getOptions() should only be available on option-set attributes, not option-set controls.

Removed after 2011:
This is actually the opposite problem. In CRM 2013 these two methods have been replaced by getClient and getClientState, but they are perfectly valid in CRM 2011. So could you add them in that case?
Xrm.Page.context.isOutlookClient
Xrm.Page.context.isOutlookOnline
