### ISSUE TITLE
XrmQuery issue when field name is the same as entity name

### ISSUE THREAD

**Issue by sowka1995** [delegateas/XrmDefinitelyTyped#160]
**Describe the bug**
I had the opportunity to meet the situation when the field on the form is named the same as the name of the entity. This causes a problem when creating requests in which we use such field.

> Error: Could not find a property named 'new_listprice' on type 'Microsoft.Dynamics.CRM.new_listprice

In this case, if we return records with all fields, instead of **'new_listprice**' we will see '**new_listprice1**'

**To Reproduce**

1. Create an Entity eg. 'new_listprice'
2. Create a field named 'new_listprice'
3. Create simple request like below:
```
XrmQuery
     .retrieveMultiple(x => x.new_listprices)
     .select(x => [x.new_listprice])
     .promise();
```

**Current workaround**
Currently, to retrieve the value of this field, omit the select clause, and then retrieve the value as follows:
```
XrmQuery
     .retrieveMultiple(x => x.new_listprices)
     .promise()
     .then(listPrices => {
          const listPriceValue = listPrices[0]["new_listprice1"];
     });
```

**Expected behavior**
It seems that the only solution to this problem is to correct generated metadata in such cases. If the field is named the same as entity then the number 1 should be at the end of the field name. Maybe there is a better solution?
Unfortunately, I can't change the name of the field, because this option generates more problems.

**Environment**
- CRM 365 Online version: 9.1.0
- Tool version: 4.4.4

**Comment by TomMalow** [comment]
We are aware of this bug but have refrained from spending time resolving this issue. We have experienced that a field with the same name as the the entity is a bad design. Normally the field would be named based on a property of an object that the entity models. They rarely tend to have the same name. 

This does not mean that the issue shouldn’t  be resolved. Simply that the easiest solution is to rename the field to something else.

**Comment by Kato88** [comment]
We still have the issue that Microsoft Apps follow this bad design. If I remember correctly it was their survey solution that had at least one entity with this issue.

**Comment by TomMalow** [comment]
Well that sucks. I can inform that we are currently working on updating XrmQuery to handle this case. However, we don't have an ETA on a fix.

**Comment by magesoe** [comment]
Added in 5.1.3

**Comment by magesoe** [comment]
Improved the way it is handled in 5.1.7
