### ISSUE TITLE
How to generate types with 2-step verification?

### ISSUE THREAD

**Issue by ahnwarez** [delegateas/XrmDefinitelyTyped#161]
Thank you so much for creating this fantastic project.

My client implements 2-step verification. Every new session, I'd have to provide a 6-digits code form Google Authenticator App to access D365 Online using the browser.

When I run XrmDefinitelyTyped.exe I get this error
```
Connecting to CRM...
Unable to generate TypeScript files: Metadata contains a reference that cannot be resolved: 'https://iam.<client name>.ac.nz/profile/SAML2/SOAP/ECP'.
```
The URL above is a redirect to insert authenticate using 6-digits, which I understand why the generation failed.

Is there a way to enforce `interactivelogin`? tried but didn't work.
Or do I have to setup an App Registration in Azure Portal as an alternative to use S2S authentication?

**Environment**
- CDS version 9.1.0000.11434

**Comment by magesoe** [comment]
The newest version of XDT supports authenticating using OAuth or ClientSecret. You can switch your method of connecting using the `method` argument https://github.com/delegateas/XrmDefinitelyTyped/wiki/Tool-usage 

You need to create an application user in your environment. This is used in both of these new authentication methods. 
For OAuth you must specify your credentials, the app id for your app registration and a public client return url.
For ClientSecret you only have to specify app id and a secret for you app registration. This method is preferred if you call XDT in a DevOps scenario.

Hopefully this works for you, it works for us :)
