### ISSUE TITLE
Caseing of PageInput interface webResourceName property

### ISSUE THREAD

**Issue by strwase** [delegateas/XrmDefinitelyTyped#163]
The casing is wrong on the webResourceName property of the PageInput interface.
It should be webresourceName, the R cant be capitalized, otherwise the Xrm.Navigation.navigateTo function throws an error.

![image](https://user-images.githubusercontent.com/10077785/73349299-40024780-428b-11ea-8c48-563e3d5081ac.png)

![image](https://user-images.githubusercontent.com/10077785/73349474-8657a680-428b-11ea-8c27-dad2f924de2b.png)

**Comment by magesoe** [comment]
Added in 5.1.0
