### ISSUE TITLE
Support for formContext.ui.quickForms

### ISSUE THREAD

**Issue by zunin** [delegateas/XrmDefinitelyTyped#164]
It would be great if XrmDefinitelyTypes supported this as well!

The client api is at https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-ui-quickforms

**Comment by henrikhannemose** [comment]
I definitely agree. This is a sought-after feature. PRs are very welcome :)

**Comment by henrikhannemose** [comment]
Duplicate of #12

**Comment by zunin** [comment]
closed as duplicate
