### ISSUE TITLE
Xrm.Utility.getGlobalContext().userSettings.securityRoles is deprecated

### ISSUE THREAD

**Issue by OliverFlint** [delegateas/XrmDefinitelyTyped#166]
Xrm.Utility.getGlobalContext().userSettings.securityRoles is deprecated and should be changed to Xrm.Utility.getGlobalContext().userSettings.roles

see https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/getglobalcontext/usersettings#securityroles

**Comment by magesoe** [comment]
Fixed in 5.1.8

**Comment by sergeytunnik** [comment]
This actually breaks working securityRoles typings and at the same time doesn't provide proper typings for roles property.
New roles property isn't array of strings. It is some XRM wrapper on collection of lookup-like objects. This collection wrapper doesn't allow any meaningful iterations over it.

Regarding removing obsolete typings.
When MS marks something as obsolete it doesn't mean it stops working immediately. securityRoles are there and work as expected both for on-prem (9.1.0.12) and online (9.1.0.14754). And I think they will be there for a next few years. And for those who is using on-prem deployment there is no alternative to securityRoles.

I understand that MS documentation may be incomplete and actually wrong. It states for roles: "Type: Array of objects" which it isn't. Also it doesn't help that MS adds new client side API without bumping major minor versions. But we can make basic sanity checks before pushing changes.

Screenshots with securityRoles, roles details for on-prem and online:
![onprem-9-1-0-12](https://user-images.githubusercontent.com/512079/77335582-07cd3180-6d2f-11ea-91d2-5138e868ff33.PNG)
![online-9-1-0-14754](https://user-images.githubusercontent.com/512079/77335611-0dc31280-6d2f-11ea-91ec-5f81eab42953.PNG)

**Comment by sergeytunnik** [comment]
Created issue in D365 docs repo: https://github.com/MicrosoftDocs/powerapps-docs/issues/1176

**Comment by magesoe** [comment]
Thank you for ensure the high quality. Seems I was a bit to quick with merging that PR. XDT has a way of splitting typings into removed, deprecated, and available. I will add that to your PR and merge it ASAP

**Comment by TomMalow** [comment]
Note that the new API does not return a list of Guids but an object with the role id and name:
https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/getglobalcontext/usersettings#roles

**Comment by robertraaijmakers** [comment]
This is the correct typing:

/**
         * An array of strings that represent the GUID values of each of the security roles that the user is associated with or any teams that the user is associated with.
         */
        roles: Collection<EntityReference<"securityrole">>;

Have implemented this in my own project xrm.d.ts for now. Hopefully this helps you implementing the fix.

**Comment by sergeytunnik** [comment]
@robertraaijmakers thanks for hints.
Unfortunately EntityReference can't be reused cause there is no entityType property on that Role object.

**Comment by robertraaijmakers** [comment]
That's correct, that's why I hard-coded it. Since it is in fact an entity reference to security role. Only not all data is supplied. It currently works in our solution this way. If there is a better option I'm glad to see it in an update and will do some rework in our current code.

p.s. I submitted a bug to Microsoft since the security role names of the security roles inherited from team are not retrieved

**Comment by magesoe** [comment]
Seems like we never closed this issue after merging your PR. it was added in 5.2.0
