### ISSUE TITLE
Add support for formContext.data.process.addOnPreStageChange

### ISSUE THREAD

**Issue by bo-stig-christensen** [delegateas/XrmDefinitelyTyped#177]
Latest Client-Side SDK for D365 contains a function addOnPreStageChange(myFunction).

The event is described here: https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/events/onprestagechange

An event handler for this event is able to prevent stage changes based on custom logic using preventDefault() on the eventArgs.

**Comment by TomMalow** [comment]
Issue resolved in version  5.3.1
