### ISSUE TITLE
addNotification Typing incorrect

### ISSUE THREAD

**Issue by strwase** [delegateas/XrmDefinitelyTyped#183]
The typing definition for the addNotification method is incorrect.
The Microsoft documentation states it needs an Array of ActionObjects, the definition in xrm.d.ts asks for just an ActionObject

![image](https://user-images.githubusercontent.com/10077785/82896611-8b391800-9f56-11ea-8ac6-0dcd914881e8.png)

![image](https://user-images.githubusercontent.com/10077785/82896643-9a1fca80-9f56-11ea-860e-cea8b3abfe74.png)

Could this please be fixed in a future update?

thanks

**Comment by TomMalow** [comment]
Issue resolved in version 5.3.0
