### ISSUE TITLE
setIsValid on attribute definition missing return type

### ISSUE THREAD

**Issue by strwase** [delegateas/XrmDefinitelyTyped#184]
The setIsValid function on the attribute class is missing its return type in the xrm.d.ts file.

![image](https://user-images.githubusercontent.com/10077785/82896956-1fa37a80-9f57-11ea-9bc0-0973217cf817.png)

Could the void return type please be added?

Thnx

**Comment by TomMalow** [comment]
Issue resolved in version 5.3.0
