### ISSUE TITLE
New project: Can't build

### ISSUE THREAD

**Issue by mcerdeira** [delegateas/XrmDefinitelyTyped#19]
After running XrmDefinitelyTyped.exe tool, can't compile:

> Error	106	Could not find symbol 'Xrm'.	C:\Users\mcerdeira\Desktop\SDK\MC\TypeScriptHTMLApp1\TypeScriptHTMLApp1\typings\XRM\Form\account\Main\Information.d.ts	74	41	Information.d.ts

I started the project as:

![image](https://user-images.githubusercontent.com/938346/30169086-bee99a24-93c1-11e7-851b-5727e42c3427.png)

I don´t know what am I doing wrong.

**Comment by mcerdeira** [comment]
This is the full project, with credentials and url blanked.

[TypeScriptHTMLApp1.zip](https://github.com/delegateas/XrmDefinitelyTyped/files/1285092/TypeScriptHTMLApp1.zip)

**Comment by henrikhannemose** [comment]
Thanks for uploading the project. It appears that your project is using an old version of TypeScript (`<TypeScriptToolsVersion>1.0</TypeScriptToolsVersion>`). Can you try updating to a newer TypeScript version?

For comparison, I can compile your project just fine with Visual Studio 2017 using TypeScript 2.2.3.

**Comment by mcerdeira** [comment]
Oh, I see. It must be related with me creating the project as a VS2013 project.
Thanks for the reply!
