### ISSUE TITLE
Support non-password login

### ISSUE THREAD

**Issue by Martype** [delegateas/XrmDefinitelyTyped#193]
Hi, I don't think it is a good design to have passwords stored as clear text in a configuration file. Wouldn't it be better if the tool does something like Sparkle XRM where you can login via cmd and store the connection in the Windows credential vault? I really would like to use XrmDefinitelyTyped but storing passwords as clear text in our git repository is a no-go.
Nice regards

**Comment by TomMalow** [comment]
We haven't added any safe storing of secrets in configuration as there are already ways to use the tools we have without needing to store secrets in configurations at all.

For our projects we do the following:

- If a developer needs to use our tools in part of the project. Then they run the tools local and input credentials to the CRM instance when prompted by the tools. If the developer does not have their own CRM admin user and needs to use a specific admin user. Then the credentials to that user is stored in another secure place such as Keypass, Password Server or other secure password managers.
- If the tools are used as part of a build/DevOps pipeline. Then that pipeline should have options to retrieve the credentials from a secure storage. That means that the pipeline retrieves the secrets when needed and apply them as parameters when calling our tools. For our case, we generally use Azure DevOps together with Azure KeyVault.

I don't have an example for running the tools from an on-prem server. But my guess is that there is another secure way to store the secrets on the server and retrieving these before calling the tools. 
Implementing our own way of securely storing secrets is in general a bad idea as we aren't 100% to do it correctly. So using another, battle tested tools, is a much better idea. (That said, we do cache the CRM secrets locally when running our Daxif tool. These secrets are encrypted so only the machine that ran Daxif can decrypt it.)

But it might be that you have another case where the methods I have mentioned is not an option?

**Comment by Martype** [comment]
I built a powershell script, but apparently username and password do not get merged with the exe.config correctly 

$credential = Get-Credential
$username = $credential.UserName
$password = $credential.GetNetworkCredential().password
$directory = Resolve-Path .\XrmDefinitelyTyped\
$path = $directory.Path
$exe = $path + "XrmDefinitelyTyped.exe"
Start-Process -FilePath $exe -WorkingDirectory $directory.Path -ArgumentList "/useconfig /username:$username /password:$password" -NoNewWindow

result: 
Connecting to CRM...
Unable to generate TypeScript files: clientCredentials.UserName.UserName or clientCredentials.Windows.ClientCredential.UserName MUST be populated!

**Comment by Martype** [comment]
> I built a powershell script, but apparently username and password do not get merged with the exe.config correctly
> 
> $credential = Get-Credential
> $username = $credential.UserName
> $password = $credential.GetNetworkCredential().password
> $directory = Resolve-Path .\XrmDefinitelyTyped
> $path = $directory.Path
> $exe = $path + "XrmDefinitelyTyped.exe"
> Start-Process -FilePath $exe -WorkingDirectory $directory.Path -ArgumentList "/useconfig /username:$username /password:$password" -NoNewWindow
> 
> result:
> Connecting to CRM...
> Unable to generate TypeScript files: clientCredentials.UserName.UserName or clientCredentials.Windows.ClientCredential.UserName MUST be populated!

Ha, never mind. I used "asd" as username and password to simply test my script, but this obviously was not ok 😄

**Comment by TomMalow** [comment]
Yeah it should work as written in our [wiki](https://github.com/delegateas/XrmDefinitelyTyped/wiki/Tool-usage#configuration-file). though I haven't used it myself.

So you got it to work?

**Comment by Martype** [comment]
Yes, my powershell script does the job. Thanks for your response. Nice regards!

**Comment by TomMalow** [comment]
I have updated the wiki page for [Getting Started](https://github.com/delegateas/XrmDefinitelyTyped/wiki/Getting-started#step-by-step) to include suggestion to pass secrets to the executable as arguments instead of storing them in the config.

Thanks for being part of improving out tools @Martype
