### ISSUE TITLE
Not able to connect to CRM

### ISSUE THREAD

**Issue by Roopamdutta** [delegateas/XrmDefinitelyTyped#196]
Dear Developer(s),
I am not able to connect to CRM using XrmDefinatelyTyped.exe and i get below error:
Unable to generate TypeScript files: An unsecured or incorrectly secured fault was received from the other party. See the inner FaultException for the fault code and detail

I am using exact format config as shown in video/documentation.

Please help, I am completely new to F# therefore not able to understand the issue

**Comment by magesoe** [comment]
Can you show us your config file, or the arguments you use to connect? Remember to anonymize your password

**Comment by Roopamdutta** [comment]
Thank you magnus for your kind prompt response, below is the config file- 

- <?xml version="1.0" encoding="utf-8"?>
- <configuration>
-   <appSettings>
-     <add key="url" value="https://orgname.api.crm8.dynamics.com/XRMServices/2011/Organization.svc" />
-     <add key="username" value="admin@orgname.onmicrosoft.com" />
-     <add key="password" value="********" />
-     <add key="out" value="typings/XRM" />
-     <add key="solutions" value="" />
-     <add key="entities" value="account, contact" />
-     <add key="web" value="" />
-     <add key="jsLib" value="src/lib" />
-     <add key="mfaAppId" value="" />
-     <add key="mfaReturnUrl" value=""/>
-   </appSettings>
- </configuration>

**Comment by magesoe** [comment]
If you're using user/pass login, then you don't need to provide mfaAppId and mfaReturnUrl. However user/pass was deprecated for new tenants in October through the API.
There error you're getting is that the login details you provided were rejected by CRM.
For more authentication options see https://github.com/delegateas/Daxif/wiki/Using-different-auth-methods

**Comment by misoeli** [comment]
Closing. Feel free to reopen if the issue persists, and we will try to assist.
