### ISSUE TITLE
Missing fields in generated typings

### ISSUE THREAD

**Issue by themike10452** [delegateas/XrmDefinitelyTyped#2]
I have a custom _activity_ entity with one Main form (**Information**), one mobile express form and one quick view form. When I generate the typings, all custom fields and sections on the **Information** form are not detected and not present in the typescript definitions. Those are all the fields that are generated:
![image](https://cloud.githubusercontent.com/assets/7006763/26199241/fc372a24-3bd1-11e7-98e9-eee71625719a.png)
![image](https://cloud.githubusercontent.com/assets/7006763/26198976/03dd075e-3bd1-11e7-84b2-ea40160e43da.png)

However, when I create a copy of **Information** form using _save as_, and regenerate the typings I get all the fields and sections like I expect:
![image](https://cloud.githubusercontent.com/assets/7006763/26199069/586ad562-3bd1-11e7-86bd-c9611b32817a.png)
![image](https://cloud.githubusercontent.com/assets/7006763/26199100/771cac24-3bd1-11e7-8ea5-29ad82236c09.png)

Deleting the copy form, and regenerating the typings results in missing fields problem again.

I noticed the form version is 0.1, and the copy form created using _save as_ has version 0.4 (Maybe because this solution was upgraded from CRM2015), but the question is why does creating a copy of the **Information** form actually help with properly generating field typings?

How can I help you pinpoint the issue?

Thanks in advance

**Update 1:**
I just deleted the old information form (version 0.1) and kept the copy (version 0.4), typings are now being generated properly. Please just close this issue if you have no interest in further debugging.
Thank you for your efforts.

**Comment by mktange** [comment]
My guess is that you did not publish the **Information** form after modifying it. Typings generated by XrmDefinitelyTyped does not include non-published changes.
