### ISSUE TITLE
v5.4.2 is published as "XrmDefinitelyTyped"

### ISSUE THREAD

**Issue by Martype** [delegateas/XrmDefinitelyTyped#201]
Does this mean, that "Delegate.XrmDefinitelyTyped" is discontinued and we should use "XrmDefinitelyTyped" instead?

![image](https://user-images.githubusercontent.com/1420317/104604119-69bfa480-567d-11eb-849f-6ec0d9cbd599.png)

**Comment by magesoe** [comment]
No, my mistake, thought I fixed that!

**Comment by magesoe** [comment]
Should be fixed now, sorry for the confusion... 
![image](https://user-images.githubusercontent.com/8904582/104605736-29f9bc80-567f-11eb-8614-122270afc718.png)
