### ISSUE TITLE
setVisible method on FormItem missing

### ISSUE THREAD

**Issue by urossavelj** [delegateas/XrmDefinitelyTyped#203]
**Describe the bug**
setVisible method on FormItem is missing, which is an officially supported API by Microsoft:

https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-ui-formselector/setvisible

**To Reproduce**
Try to use setVisible method on a FormItem. You will get an error TS2339: (TS) Property 'setVisible' does not exist on type FormItem

**Expected behavior**
setVisible method should be implemented on FormItem.

**Environment**
- CRM/D365/CDS version: v9
- Tool version: 5.4.2

**Additional context**
The fix is done easily just by adding the setVisible method in xrm.d.ts. 
I already created a pull request for this fix, #202

**Comment by magesoe** [comment]
Was added in 5.4.4, forgot to close the issue :)
