### ISSUE TITLE
formContext.ui.tabs.get doesn`t exist

### ISSUE THREAD

**Issue by VikariiCGI** [delegateas/XrmDefinitelyTyped#206]
Hi,
Would you kindly please get function for tabs 
https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-ui-tabs

**Comment by magesoe** [comment]
What is missing from the current implementation? It generates fine in the latest version
![image](https://user-images.githubusercontent.com/8904582/108982796-7678e480-768e-11eb-8516-bb595564ce24.png)

**Comment by VikariiCGI** [comment]
Strange, I see only this 
![image](https://user-images.githubusercontent.com/74358381/108983645-c1e3c080-7697-11eb-9763-287f840a8353.png)

**Comment by magesoe** [comment]
Is the form object a formContext? 
![image](https://user-images.githubusercontent.com/8904582/108983978-b9878780-768f-11eb-8868-91ea85747a8a.png)

**Comment by VikariiCGI** [comment]
I`m trying to create common function
```
export function getSection(
  form: Xrm.PageBase<
    Xrm.AttributeCollectionBase,
    Xrm.TabCollectionBase,
    Xrm.ControlCollectionBase
  >,
  tabName: string,
  sectionName: string
) {
     form.ui.tabs.get(tabName);
}
```

**Comment by magesoe** [comment]
A generic function on PageBase would probably not work. Instead I would use the [form intersection](https://github.com/delegateas/XrmDefinitelyTyped/wiki/Form-intersections) functionality to get form type for the forms you want to be generic on. The purpose is to be explicit about where your logic is run

**Comment by VikariiCGI** [comment]
Ok, I see "get" works from exactly specific form.
Thanks !
