### ISSUE TITLE
KB Search Control typings

### ISSUE THREAD

**Issue by kschepperly** [delegateas/XrmDefinitelyTyped#209]
XDT Version: 5.4.4
Dynamics CRM 365 Version: 8.2.1.342

I am currently working with a KB Search control on entity forms and there seems to be no typings defined. Is there any way to handle the set of methods below using XRMDefinitelyTyped? The generated typings from XDT declare my control as a basic Xrm.BaseControl.

<pre>get(name: "kbSearch"): Xrm.BaseControl;</pre>

I see kbsearch is defined in the ControllType, but there is no corresponding interface to handle its methods. 
<pre>type ControlType = 
    "standard" | 
    "iframe" | 
    "lookup" | 
    "optionset" | 
    "subgrid" | 
    "webresource" | 
    "notes" | 
    "timercontrol" | 
    <b>"KBSEARCH"</b> | 
    "multiselectoptionset";</pre>

I am only seeing these types below:

- BaseControl
- WebResourceControl
- IFrameControl
- LookupControl<string>
- SubGridControl<string>
- DateControl
- OptionSetControl<any>;

The KB Search Control would require the methods below.

[Knowledge base search control methods](https://docs.microsoft.com/en-us/previous-versions/dynamicscrm-2016/developers-guide/dn932131(v=crm.8)#knowledge-base-search-control-methods) <- Link to Microsoft references
- addOnPostSearch
- addOnResultOpened
- addOnSelection
- getSearchQuery
- getSelectedResults
- getTotalResultCount
- openSearchResult
- removeOnPostSearch
- removeOnResultOpened
- removeOnSelection
- setSearchQuery

**Comment by magesoe** [comment]
Added in 5.4.5
