### ISSUE TITLE
Run.ps1 relative execution directory incorrect

### ISSUE THREAD

**Issue by bo-stig-christensen** [delegateas/XrmDefinitelyTyped#22]
The Run.ps1 script may be run in a couple of ways.
Running it in PowerShell ISE or PowerShell Console directly will have the working directory set to the script directory and the script works fine.

However, if executing from Visual Studio using the context menu's "Execute as Script", the working directory is the current project's directory and execution fails.

A slight modification to Run.ps1 fixes this:
```
Push-Location (split-path $SCRIPT:MyInvocation.MyCommand.Path -parent)
.\XrmDefinitelyTyped.exe
```

This ensures that the working directory is always the same as the script directory and will work regardless of executing from command line or from Visual Studio context menu.

**Comment by magesoe** [comment]
Nice. Currently we don't use it when we test, since we test by using the nuget package locally, but we will check if this modification will fix the script

**Comment by magesoe** [comment]
Nice. Currently we don't use it when we test, since we test by using the nuget package locally, but we will check if this modification will fix the script
