### ISSUE TITLE
Generate formIntersect throws exception

### ISSUE THREAD

**Issue by strwase** [delegateas/XrmDefinitelyTyped#225]
I'm trying to generate a formIntersect

but I keep getting an error

![image](https://user-images.githubusercontent.com/10077785/120641311-be6c8c00-c473-11eb-8df6-c9db4acf4d76.png)

as far as I can tell, my config is correct

![image](https://user-images.githubusercontent.com/10077785/120641365-d0e6c580-c473-11eb-9a39-5df96e26f39f.png)

Any help would de appreciated

**Comment by misoeli** [comment]
The config for formintersect is missing a closing "/". I get the same error without it, but correct output with it in place

**Comment by strwase** [comment]
deez, now i feel like a complete idiot :-)

**Comment by skovlund** [comment]
If that is the case we should update the documentation to reflect the need for that slash. However, I'm not experiencing this issue, when running with full XrmFramework setup, i.e. executing through fsi not cmd/PS.
![image](https://user-images.githubusercontent.com/7383967/120761225-4060c180-c515-11eb-824f-4fa75a6c8cb6.png)

**Comment by misoeli** [comment]
It's not needed in fsi - it's the xml tag close slash, that was missing.
![image](https://user-images.githubusercontent.com/1128002/120780918-db16cb80-c528-11eb-9dbb-a842c683c21d.png)
