### ISSUE TITLE
Update Default Version?

### ISSUE THREAD

**Issue by daryllabar** [delegateas/XrmDefinitelyTyped#229]
Currently the Default version is 8.0.  I'm not aware of anyway to set this in WebPack via setApiVersion, so I'd have to set it every time I want to use.  Any chance that there is a way to configure this?  Maybe in the config?  Any issues with using 9.2 that are known?

**Comment by magesoe** [comment]
Imo we should just bump it to the latest always whenever a new version comes out, and then people can manually downgrade if they want to

**Comment by daryllabar** [comment]
So maybe the next version will set the default to 9.2, rather than 8.0?  I also think having a config value would be helpful for people stuck on prem.

**Comment by daryllabar** [comment]
Any idea when I could expect this to be implemented?  Not trying to pressure or anything, but I'm just trying to figure out if I want to "head off in another direction"

**Comment by misoeli** [comment]
Updated in 5.5.2.
