### ISSUE TITLE
Attribute "directioncode" gets type number instead of boolean in Form.phonecall

### ISSUE THREAD

**Issue by lisbyschmidt** [delegateas/XrmDefinitelyTyped#23]
The attribute "directioncode" is of type boolean on all other activities. However, on phonecall forms the type is number. Interfaces PhoneCall_Base, PhoneCall_Select and PhoneCall_Filter correctly show "directioncode" as boolean.

> get(name: "directioncode"): Xrm.OptionSetAttribute< number>;
> get(name: "directioncode"): Xrm.OptionSetControl< number>;
> getAttribute(attributeName: "directioncode"): Xrm.OptionSetAttribute< number>;
> getControl(controlName: "directioncode"): Xrm.OptionSetControl< number>;
> 
> interface PhoneCall_Base extends WebEntity {
> ...
>   directioncode?: boolean | null;
> ...
> }
> 
> interface PhoneCall_Select {
> ...
>   directioncode: WebAttribute<PhoneCall_Select, { directioncode: boolean | null }, {  }>;
> ...
> }
> 
> interface PhoneCall_Filter {
> ...
>   directioncode: boolean;
> ...
> }

**Comment by magesoe** [comment]
I have been unable to reproduce this bug on CRM 2016, which version of CRM did the bug occur on?

**Comment by lisbyschmidt** [comment]
The bug occurs on our CRM 2011 organization. But I have also seen it on CRM 2016 after a test-migration of this organization.

**Comment by lisbyschmidt** [comment]
I have found out how to reproduce the bug. It occurs when the field is present on the form and the control is formatted as "List". When using "Two radio buttons" or "Check box" the type is correctly boolean instead of number.
