### ISSUE TITLE
Generated types missing some fields

### ISSUE THREAD

**Issue by szmarci** [delegateas/XrmDefinitelyTyped#230]
**Describe the bug**
A have a custom Lead form:

![image](https://user-images.githubusercontent.com/1974290/124145319-f83dac00-da8c-11eb-845e-8ac6e2602ab5.png)

When I generate types, some fields are missing for some reason:

![image](https://user-images.githubusercontent.com/1974290/124145477-202d0f80-da8d-11eb-9152-cffacb2ec694.png)

All the fields are published on the form as can be seen on the screenshot.

**Environment**
- CRM/D365/CDS version: 9.2.21055.00135
- Tool version: 5.5.1

**Comment by misoeli** [comment]
When I'm looking at the default form, first name and last name are shown when the name field is shown. Are you sure, your form contains the individual fields, and not the composite one?

Another possibility is that your formContext type refers to another form than your custom form. Have you checked the type actually matches your form, and not the default form?

**Comment by szmarci** [comment]
@misoeli Ah, you are right, it was the composite field. Thanks, I'm closing this.
