### ISSUE TITLE
Static-/Basic-Page for non-formspecific scripts

### ISSUE THREAD

**Issue by Flydancer** [delegateas/XrmDefinitelyTyped#24]
Hi Guys,
is it possible to add the default XRM-Objectmodel functions (for instance XRM.Page.getControl()) in xrm.d.ts so that they're usable in non form-specific scripts (utlity-classes)? I've extended the xrm.d.ts with some of these functions by myself but i've to copy&paste after every new metadata-generation.

Another great option would be the possibility to rename the default Namespace from Xrm to something else.

Thanks,
Alex

**Comment by henrikhannemose** [comment]
Can you give a small example of such a helper function and what your extension to `xrm.d.ts` is? I am not sure I follow how you want to use e.g. `Xrm.Page.getControl()` without being in the context of a form.
Maybe [form intersections](https://github.com/delegateas/XrmDefinitelyTyped/wiki/Form-intersections) can be useful in your case?

**Comment by Flydancer** [comment]
Hi henrik,
thanks for your fast response.
I have a so called "utilities" library. Let's take autocomplete as an example:

```
    export async function InitAutocomplete(entityName: string, fieldName: string) {
        var acData = await RetrieveAutocompleteValues(entityName, fieldName);
        var keyPressFn = function (ext) {
            try {
                var userInput = **Xrm.Page.getControl(fieldName)**.getValue().toLowerCase();
....
```
It shows me an error, because there is no .getControl for Xrm.Page (no form specification declared).
To solve this i've added `getControl(controlName: string): BaseControl;` to the PageBase interface in xrm.d.ts

I'm new to typescript and maybe i'm doing something horribly wrong. How would be the best way to use these functions "globally"?

Thanks a lot,
Alex

**Comment by mktange** [comment]
Currently, the best way to achieve what you are looking for (without resorting to casting `Xrm.Page` to the `any` type) is to pass in the control/attribute itself, instead of just the field name.

So in your example, it would be something like:

```typescript
    export async function InitAutocomplete(entityName: string, control: Xrm.Control<any>) {
        var acData = await RetrieveAutocompleteValues(entityName, control.getName());
        var keyPressFn = function (ext) {
            try {
                var userInput = control.getValue().toLowerCase();
....
```

**Comment by Flydancer** [comment]
Hi mktange,
thanks for your response. 
Your suggestion doesn't work, too because the Control/BaseControl Interface doesn't have the getValue() function.
So (for now) i will stay with my manually edited xrm.d.ts because i don't have to rewrite all existing scripts that access the utility lib (with string parameters) then.

Sorry if offtopic:
How do i correctly set a lookupvalue with a new EntityReference?
The only way i could compile without errors is
```
var lookupval = Array<Xrmdt.EntityReference>(<Xrmdt.EntityReference>{ id: product.productid, name: product.name, entityType: "product" });
Xrm.Page.getAttribute("new_versandartikelid").setValue(lookupval);
```
but it feels wrong somehow :)

Edit: Would you guys mind to share some samples how you use XrmDefinitelyType/XrmQuery in the Wiki-section?

Edit2: "addOnKeyPress()" is also missing in xrm.d.ts

Thanks in advance,
Alex

**Comment by henrikhannemose** [comment]
You are correct that there is no `.getValue()` on a control (that is just an error in your original example that was carried over). Substitue `Xrm.Control<any>` for `Xrm.Attribute<any>` in that case, and modify your code accordingly.
The concept of sending controls or attributes to your helper functions still represents best practices.

It seems that you correctly understand the concept of setting EntityReferences. I personally prefer the following syntax with fewer explicit types:
```
Form.getAttribute("new_versandartikelid").setValue([{ id: product.productid, name: product.name, entityType: "product" }]);
```

It is a good idea to add more examples to the documentation. Time is a limiting factor though, so you are also very welcome to document your lessons learned in some blog posts :)
