### ISSUE TITLE
Connection string

### ISSUE THREAD

**Issue by peterbjorkmarker** [delegateas/XrmDefinitelyTyped#254]
**Is your feature request related to a problem? Please describe.**
I would like to connect with a connection string so I can use certificate authentication. I had a look at the code and it seems to be implemented already. Correct? If so, would you be ok if I update the documentation?

**Describe the solution you'd like**
Update the docs to include ConnectionString as the method and the /connectionString parameter

Thanks!

**Comment by misoeli** [comment]
You're right, it is supported, but was never added to the documentation. It is now ->[https://github.com/delegateas/XrmDefinitelyTyped/wiki/Tool-usage](https://github.com/delegateas/XrmDefinitelyTyped/wiki/Tool-usage).
