### ISSUE TITLE
Typings for setCurrentView

### ISSUE THREAD

**Issue by skovlund** [delegateas/XrmDefinitelyTyped#258]
**Describe the bug**
Typings for `viewSelector.setCurrentView(object);` assume the parameter 'object' is of type `EntityReference<string>`.
This typing forces the `entityType` part of the `object` to be `string`, but it should be a `number`.

**To Reproduce**
1. Generate typings for a form with a subgrid, where the viewselector is enabled
2. Add formscripting that uses `viewSelector.setCurrentView(object);`

**Expected behavior**
Typings that match the [documentation](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/grids/viewselector/setcurrentview) i.e., `entityType` is a `number` and not a `string`.

**Screenshots**
![image](https://user-images.githubusercontent.com/7383967/155133656-31f2f26f-d6ec-47e3-a530-42c94ca4f520.png)

**Environment**
- XrmDefinitelyTyped v. 5.4.2

**Comment by mkholt** [comment]
Note: It's not any number, it's the object type code for either SavedQuery (1039) or UserQuery (4230).
This should probably be generated as a const enum and compile-time replaced with the respective number.
![image](https://user-images.githubusercontent.com/4355246/155137189-8e628d4c-a2f2-4792-a6bd-b4cad88321b0.png)
