### ISSUE TITLE
Cannot generate files due to Authentication error

### ISSUE THREAD

**Issue by szmarci** [delegateas/XrmDefinitelyTyped#264]
**Describe the bug**

Yesterday it was working, but now we are getting this error:

Unable to generate TypeScript files: An error occurred when processing the security tokens in the message: You are using Ws-Trust authentication which has been deprecated and no longer supported in your environment. Please use OAuth2.0 authentication.

**Comment by misoeli** [comment]
Already supported - see [DAXIF documentation](https://github.com/delegateas/Daxif/wiki/Using-different-auth-methods).
While that documentation is written for F#, the arguments are the same in a config file or command line, and reusable across all tools.

**Comment by szmarci** [comment]
So from now on I can only get this tool to work if I generate an app id & secret in azure portal?

**Comment by skovlund** [comment]
I've updated the documentation, which now also includes the sample app id provided by Microsoft. But the recommended approach is to generate an app registration yourself. It does not need a secret though.

**Comment by szmarci** [comment]
@skovlund Thanks, can you give me a link to that? I can't seem to find it.

**Comment by skovlund** [comment]
Sorry, I updated the [DAXIF documentation](https://github.com/delegateas/Daxif/wiki/Using-different-auth-methods) which might not have been clear from my comment.

**Comment by szmarci** [comment]
I see, thanks!
