### ISSUE TITLE
Editable Grid set as BaseControl

### ISSUE THREAD

**Issue by tpb1109** [delegateas/XrmDefinitelyTyped#274]
When using getControl() on an editable grid it is being given the BaseControl type rather than SubGrid. This only happens when I add the Editable Grid control to the grid, if I remove it and leave the read-only one then it works fine.

My code still works fine when using an editable grid, and I am currently handling this by editing the interfaces in the context.d.ts file so that is using Xrm.SubGridControl rather than Xrm.BaseControl, but I was just making sure there isn't something I'm missing to handle this better.

**Comment by OliverFlint** [comment]
FYI, same issue with the new Power Apps Grids
