### ISSUE TITLE
Cannot find namespace VS 2022

### ISSUE THREAD

**Issue by Marvinnnne** [delegateas/XrmDefinitelyTyped#281]
I've worked on VS 2019 and all works fine. When I upgrade to 2022, i'm facing this issue

Cannot find namespace 'Form' or 'Xrm' either all namespace in typings folder

This is my tsconfig.json : 
![image](https://user-images.githubusercontent.com/9744563/205054707-158d20c6-98d1-4cb9-a567-3d232ae5b222.png)

I have deleted folder Xrm in order to regenerate it but it doesn't work.

Do you have any idea what is difference between VS 2019 and 2022 ?

Best regards,

**Comment by janis-veinbergs** [comment]
In which folder does your XrmDefinitelyTyped typings live? Under src ? If not, add another include path that would include xrmdefinitelytyped .d.ts files. See https://github.com/delegateas/XrmDefinitelyTyped/issues/117#issuecomment-551118130

**Comment by Marvinnnne** [comment]
Hello, 

i've updated my tsconfig file because typing folder is not under src but i've still this error. 

I don't understand why there is a difference between VS 2019 and VS 2022.
![tsconfig](https://user-images.githubusercontent.com/9744563/224938990-0ae4a250-3b01-4d12-b76c-1e221a0f33c4.png)
![arborescence](https://user-images.githubusercontent.com/9744563/224940209-e2803162-3e16-4e58-b97d-ef3fc6b87435.png)
![error](https://user-images.githubusercontent.com/9744563/224940484-d884f6f1-ff9e-444b-8cfd-3c8373a32c87.png)
![directory](https://user-images.githubusercontent.com/9744563/224942667-f42a694f-7bfa-4d77-8e08-47a05b48cc78.png)

**Comment by janis-veinbergs** [comment]
Huh, weird. You could try restarting VS. Otherwise maybe some MSBuild typescript properties get into the way. Anyways VS should pickup tsconfig.json as source of truth: https://www.typescriptlang.org/docs/handbook/compiler-options-in-msbuild.html

Another thing you could try adding a reference to file where form is declared and see how it goes:
`/// <reference path="path.to.d.ts" />`
