### ISSUE TITLE
Association and disassociation in XrmQuery

### ISSUE THREAD

**Issue by henrikhannemose** [delegateas/XrmDefinitelyTyped#31]
Add support for [association and disassociation](https://msdn.microsoft.com/en-us/library/mt607875.aspx).

An answer to the following StackOverflow-question can be made once this has been implemented: [xrmquery.update -> update crm id binding with null](https://stackoverflow.com/questions/46787144/xrmquery-update-update-crm-id-binding-with-null)

**Comment by EmilieLildholdt** [comment]
Support for Associate and Disassociate with tests are added **to branch "associate"** (see commit 032d830).
The solution is missing typings for the relation in both methods.

**Comment by henrikhannemose** [comment]
Assigning to @magesoe for taking a look at the code in this branch and potentially merging.
