### ISSUE TITLE
XrmQuery.update not working?

### ISSUE THREAD

**Issue by plantoschka** [delegateas/XrmDefinitelyTyped#34]
I'm trying to use the XrmQuery.update function:

```javascript
            var entity: skd_customernotification = {
                statuscode: skd_customernotification_statuscode.Approved,
                skd_approvedon: new Date(),
                skd_ApprovedBy_bind$systemusers: "/systemusers(" + Page.context.getUserId() + ")"
            };

            XrmQuery.update(x => x.skd_customernotifications)
                .setData(Page.data.entity.getId(), entity)
                .execute(x => {
                    displayNotificationWithTimeout("Approved", "INFO", "id", 5000)
                }, x => {
                    errorHandler(x.message)
                })
```

I'm always getting the message that there is an error in the query syntax. 

If I output the query string I don't see any data from my entity:
```javascript
var test = XrmQuery.update(x => x.skd_customernotifications)
                .setData(Page.data.entity.getId(), entity)
                .getQueryString();
```

Am I doing something wrong?

**Comment by magesoe** [comment]
The issue is related to the way CRM returns Guids through the frontend API. The Guids are wrapped in curly brackets, which previously caused XrmQuery to fail. The fix is part of nuget 2.3.10.

**Comment by mktange** [comment]
Also, when binding entity references, XrmQuery automatically adds the whole `/systemusers(GUID)` for you, so you should not do this yourself, but instead just pass in the GUID. 
In your example it should instead look like: 

```typescript
var entity: skd_customernotification = {
  statuscode: skd_customernotification_statuscode.Approved,
  skd_approvedon: new Date(),
  skd_ApprovedBy_bind$systemusers: Page.context.getUserId()
};
```

And as @magesoe mentioned, you may also need to remove any starting and ending curly braces from the GUID, before sending it to the Web API.

**Comment by mktange** [comment]
And the `getQueryString()` just returns the query string and not the data that will be sent with the request, which would be your entity data in this case.
