### ISSUE TITLE
RetrieveMultiple Filter.equals Guid

### ISSUE THREAD

**Issue by plantoschka** [delegateas/XrmDefinitelyTyped#35]
I've encountered a problem today with the retrieve multiple function.

I am trying to retrieve multiple records of my intersection entity that match the GUID of the currently open record:
```javascript
XrmQuery.retrieveMultiple(x => x.skd_customernotification_navcompanyset)
    .select(x => [x.skd_customernotificationid])
    .filter(x => Filter.equals(x.skd_customernotificationid, Page.data.entity.getId()))
    .execute(navCompanies => {
        // Do something
        }
    }, x => errorHandler(x.message))
```

Problem is x.skd_customernotifcationid is of type XQW.Guid while Page.data.entity.getId() is of type string. When I try to cast the string to a guid like:
```javascript
Filter.makeGuid(Page.data.entity.getId());
```
I still get the following error:
A binary operator with incompatible types was detected. Found operand types 'Edm.Guid' and 'Edm.String' for operator kind 'Equal'."

Am I doing something wrong?

**Comment by skovlund** [comment]
You have an extra `}`.
Your previous issue #21 has not been fixed for filters. You'll therefore have to strip the brackets from the id before calling `Filter.makeGuid`. 
I assume you get the error in runtime?

**Comment by plantoschka** [comment]
Thank you. Stripping the parenthesis from the second guid worked.
