### ISSUE TITLE
XrmQuery: Unable to properly parse function

### ISSUE THREAD

**Issue by zaha** [delegateas/XrmDefinitelyTyped#36]
Hi,

I just found this awesome project and tried it today. Not sure if this is a bug or I am doing something wrong, but I tried to use the Web API lib to retrieve an account on the Opportunity form like this:

```js
const accountLookup = Xrm.Page.getAttribute("parentaccountid").getValue();

const account = await XrmQuery.retrieve(x => x.accounts, accountLookup[0].id)
	.select(x => [x.accountnumber])
	.promise();
```

When I execute this, I get the following error message:

> Uncaught (in promise) Error: XrmQuery: Unable to properly parse function: x => x.accounts
    at f (tv_xrmquery.web.js?ver=-1324898337:1)
    at h (tv_xrmquery.web.js?ver=-1324898337:1)
    at c (tv_xrmquery.web.js?ver=-1324898337:1)
    at Function.e.Get (tv_xrmquery.web.js?ver=-1324898337:1)
    at Object.t.retrieve (tv_xrmquery.web.js?ver=-1324898337:1)
    at tv_opportunity.js?ver=-1324898337:23
    at Generator.next (<anonymous>)
    at tv_opportunity.js?ver=-1324898337:6
    at new Promise (<anonymous>)
    at __awaiter (tv_opportunity.js?ver=-1324898337:2)

I added the `dg.xrmquery.web.promise.min.js` file as "tv_xrmquery.web.js" web resource to the opportunity form. 

Am I doing something wrong or is this a bug?

Cheers
Michael

**Comment by zaha** [comment]
Any news on this issue?
I'm afraid this is blocking my current work and therefore rather important to me.

**Comment by mktange** [comment]
My guess is that your TypeScript target is ES6 or higher? Try setting it to ES5.

**Comment by zaha** [comment]
Hi @mktange,

thanks for your quick reply. That is right, I target ES6 since I want to utilize async/await in my code as it makes working with async stuff way easier. I set it to ES5 but then promises start to cause errors:

> An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.

I'm not quite sure what's wrong here. To my understanding, TypeScript should automatically polyfill here. I googled the problem. According to the error message and most people I included the following in my `tsconfig.json`:

```js
"lib": [ "es2015" ]
```

Doing this starts causing lots of other errors like:
> error TS2304: Cannot find name 'console'.
> error TS2304: Cannot find name 'window'.
> error TS2304: Cannot find name 'XMLHttpRequest'.

Which where working fine before adding the lib. Sorry if this may look silly, I'm quite new to TypeScript devlopment. What's wrong here?


On another note: Will ES6 be supported by XrmDefinitelyTyped?

**Comment by mktange** [comment]
Just add `"dom"` to the lib setting as well, in order to (re-)enable typings for DOM-specific stuff (like `console`, `window`, etc.):

```json
"lib": [ "es2015", "dom" ]
```

I don't think it's a priority to make XrmQuery support ES6 at the moment. At least not until all major browsers also support ES6 (arrow-functions in this case, _cough_**InternetExplorer**_cough_).

**Comment by zaha** [comment]
It's working now, thanks a lot!
I'm a little bit embarrassed now as it looks pretty obvious in hindsight 😅

**Comment by obkirneh** [comment]
@zaha : Don't be embarrassed. I was struckling with the same issue and found this post very helpfull.
Thanks @mktange for clearifying.
