### ISSUE TITLE
tsconfig typeRoots

### ISSUE THREAD

**Issue by devkeydet** [delegateas/XrmDefinitelyTyped#39]
Do you know how to get tsconfig "typeRoots" working?  Here's what I have:
{
  "compileOnSave": true,
  "typeAcquisition": {
    "enable": false
  },
  "compilerOptions": {
    "outDir": "js",
    "target": "es5",
    "sourceMap": true,
    "typeRoots": [
      "./typings/*",
      "./node_modules/@types"
    ],
    "types": [
      "XRM",
      "jquery"
    ]
  },
  "include": [
    "./ts/**/*"
  ]
}

I get intellisense for jquery, but not your typings.

**Comment by magesoe** [comment]
XrmDefinitelyTyped generates typings dynamically, therefore it's not on npm (Node Package Manager). As [this comment](https://stackoverflow.com/a/40326719/1439549) explains, types and typeRoots refers to packages from npm. 

Instead you should generate your typings with XrmDefinitelyTyped and include them in your tsconfig, as shown [in our wiki](https://github.com/delegateas/XrmDefinitelyTyped/wiki/Getting-started).

**Comment by devkeydet** [comment]
I understand all that.  However, your wiki says:

Make sure your tsconfig.json file includes the generated typings in the TypeScript context

What does that mean?  I thought, perhaps, by adding the "typings" folder (which you generate) in the "typeRoots" section of tsconfig.json and adding "XRM" which is the subfolder under "typings" in the tsconfig.json, it would give me intellisense.  I still don't understand how to get intellisense other than manually adding a /// reference at the top of the file.

**Comment by devkeydet** [comment]
Sorry, rereading "this comment" to hopefully figure it out.

**Comment by devkeydet** [comment]
Ok, so I tried this, but still no intellisense:

`{
  "compileOnSave": true,
  "typeAcquisition": {
    "enable": false
  },
  "compilerOptions": {
    "outDir": "js",
    "target": "es5",
    "sourceMap": true
  },
  "include": [
    "ts/**/*",
    "typings/**/*"
  ]
}`

Have you gotten this working using "include"?

**Comment by devkeydet** [comment]
I also tried this:
`{
  "compileOnSave": true,
  "typeAcquisition": {
    "enable": false
  },
  "compilerOptions": {
    "outDir": "js",
    "target": "es5",
    "sourceMap": true,
    "baseUrl": ".",
    "paths": {
      "*": [
        "./typings/*"
      ]
    }
  },
  "include": [
    "ts/**/*"
  ]
}`

Neither seem to work.

**Comment by henrikhannemose** [comment]
If your typings are placed in a subfolder compared to the location of your tsconfig.json, you do not need to explicitly have any includes (from [tsconfig.json](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html)):

> If the "files" and "include" are both left unspecified, the compiler defaults to including all TypeScript (.ts, .d.ts and .tsx) files in the containing directory and subdirectories [...]

Would it work for you to not explicitly specify the location of your typings by simply not having the "include" property (otherwise I think "**/*.ts" should do the trick, if you want to specify it explicitly)?

**Comment by devkeydet** [comment]
Removing "include" works.  Guess I am just being overly controlling and wanting to "optimize" by using tsconfig.json to only look at what I explicitly tell it to look at.  I cleaned some things up and this time the following works:

`{
  "compileOnSave": true,
  "typeAcquisition": {
    "enable": false
  },
  "compilerOptions": {
    "outDir": "js",
    "target": "es5",
    "sourceMap": true
  },
  "include": [
    "ts/**/*",
    "typings/**/*"
  ]
}`

I can't really tell any difference between it and one of my previous attempts, but it works.
