### ISSUE TITLE
XrmQuery: Retrieve returns name field with added "1" for custom entity

### ISSUE THREAD

**Issue by zaha** [delegateas/XrmDefinitelyTyped#40]
Hi everyone,

I just ran into a strange problem: I wanted to query a custom "Country" entity using XrmQuery Web API like this:

```js
const country = await XrmQuery.retrieve(x => x.tv_countries, countryValue.id)
    .select(x => [ x.tv_country ]) // Name attribute of the entity
    .promise();
```

But this lead to an error: 
> Could not find a property named 'tv_country' on type 'Microsoft.Dynamics.CRM.tv_country'.

Curious, I made a select retrieving all properties of `tv_country` once using XrmQuery and once using my Browser which resulted in the following curiosity:

```js
// XrmQuery
{
    tv_country1: "United States",
    // ...
}

// Browser
{
    tv_country: "United States",
    // ...
}
```

XrmQuery has added a "1" to the name field of the entity. My best guess would be this is due to the property and entity sharing their name (tv_country). For other custom entities the name field has a "name" suffix and no such problems occur. I have no idea why the name field does not have a name suffix for countries as well.

Is this a bug in XrmQuery or is there something wrong with the country entity?

**Comment by TomMalow** [comment]
Hi Michael

This is an error in XrmQuery and it is as you have described. The Web API expect any fields that have the same name as the entity to be appended with a "1". However, XrmDefinitelyTyped generates the entity and field based on the metadata in CRM where the field is not appended with a "1".

We have to change XrmDefinitelyTyped either generate the typing with "1" or to modify the send request so that the field is appended  with a "1"

**Comment by Tolini** [comment]
I have tried replicating your issue, but i have not be able to. 
Can you check and make sure that it still exists for you and if so send us a  solution with the entity so we can figure out what goes wrong?

**Comment by zaha** [comment]
Hi @Tolini 
sorry for the late response. Alas I can confirm the issue still happening with 4.0.2. I've attached a solution for v8.2 with the entity causing the trouble. Hope it helps!

[XrmQueryBug_1_0_0_0_managed.zip](https://github.com/delegateas/XrmDefinitelyTyped/files/2356758/XrmQueryBug_1_0_0_0_managed.zip)

**Comment by zaha** [comment]
Any news on this?
Error still persists in 4.3.5

**Comment by TomMalow** [comment]
Hi @zaha 
We haven't had the time to look at a fix to this issue since we haven't experienced it our self. Of course we would like to fix it but we don't have that much time on our hands.

We have talked about the solution and XrmQuery should be updated when sending the request to handle this edge case. Not update the field metadata that we retrieve from CRM.

**Comment by zaha** [comment]
Hi @TomMalow 

although inconvenient for me I can totally understand that. Maybe I will have some time to look into this. Can you give me some pointers where to start looking for a fix? 

If I'll get anything done I'll create a pull request.

**Comment by magesoe** [comment]
This issue has been solved in version 5.1.3. Can you confirm it works for you?

**Comment by zaha** [comment]
@magesoe Sorry for the long wait. I've checked and the generated type now correctly includes a `tv_country1` field in the XrmQuery select function. The returned type, however, doesn't know the selected attribute:
![image](https://user-images.githubusercontent.com/1721211/80494806-65c0ea80-8967-11ea-87f8-14b0d2d705b1.png)

> Property 'tv_country1' does not exist on type 'tv_country_Fixed'. Did you mean 'tv_countryid'?

Maybe it's a misunderstanding from my side, but shouldn't the returned type know about the field?

**Comment by mkholt** [comment]
It looks like the generated `_Select` type does not specify a type for the postfixed attribute:
![image](https://github.com/delegateas/XrmDefinitelyTyped/assets/4355246/f814235b-f10a-45f5-acfb-7a95ae33eaf0)

This may have an influence on your issue, but also makes it impossible to enable the `noImplicitAny` rule in TypeScript
