### ISSUE TITLE
Property Page does not exist on typeof Xrm

### ISSUE THREAD

**Issue by GianiWVL** [delegateas/XrmDefinitelyTyped#41]
Just started using the tool, looks promising but Its not working form me (or I'm forgetting about something).

![screenshot_14](https://user-images.githubusercontent.com/7693041/33540539-e4fb3ea8-d8cb-11e7-9d55-dd04e4005306.png)

**Comment by GianiWVL** [comment]
I was using 2.4.0. I now downgraded to 2.3.0 and it seems to work.

**Comment by skovlund** [comment]
`Xrm.Page` was deprecated in [version 9.0](https://docs.microsoft.com/en-us/dynamics365/get-started/whats-new/customer-engagement/important-changes-coming#some-client-apis-are-deprecated). XrmDefinitelyTyped does not provide typings for deprecated features.

For version 9.0+ your client scripting should instead get the context as a parameter passed to the `onLoad` function:

```
  var Form: Form.contact.Main.Information;

  export function onLoad(executionContext: Xrm.ExecutionContext<any>) {
    Form = <Form.contact.Main.Information> executionContext.getFormContext();
```
Remember to tick 'Pass execution context as first parameter' in CRM, when adding your function to the Form.

As an alternative it is possible to force XrmDefinitelyTyped to generate typings for deprecated features, using the parameter [`useDeprecated`](https://github.com/delegateas/XrmDefinitelyTyped/wiki/Tool-usage#arguments).

Using v2.3.0 simply ignores the problem as the version is older than CRM 9.0, and therefore does not handle the deprecation.

**Comment by GianiWVL** [comment]
Ooh ok. 

Haven't found a resource describing this (I think), I thought something was wrong.

Thanks a lot!
