### ISSUE TITLE
Update wiki to reflect deprecations in v9

### ISSUE THREAD

**Issue by henrikhannemose** [delegateas/XrmDefinitelyTyped#42]
It can be confusing to users that the example given in the [wiki ](https://github.com/delegateas/XrmDefinitelyTyped/wiki/Form-scripting) does not work with v9, where `Xrm.Page` has been deprecated. 

Update the wiki with examples of how to do form scripting with v9 (maybe using https://github.com/delegateas/XrmDefinitelyTyped/issues/41#issuecomment-348891107 as a starting point).

**Comment by Tolini** [comment]
Alternative information about how to access form data when developing for v9 has been added
