### ISSUE TITLE
xrm.d.ts - missing properties ?

### ISSUE THREAD

**Issue by gashupl** [delegateas/XrmDefinitelyTyped#50]
Xrm.

Hi. 
I'm trying to use XrmDefinitelyTyped tool (2.5.2) version against Dynamics 365 9.0 ogranization (on-line). 
However I have realized that there are some properties missing inside generated xrm.d.ts file. 
For example:
1. There is no  var Page: Xrm.PageBase<Xrm.AttributeCollectionBase, Xrm.TabCollectionBase, Xrm.ControlCollectionBase> property inside Xrm namespace (and interface). 
2. PageBase interface does not have a context (Xrm.context) property. 

I'm not sure is something not working correctly (or I'm doing something wrong) or maybe the programming model for generated definitions has changed in this version (if so - is there any documentation available?)?

I'm attaching my generated xrm.d.ts file (zipped) to this report. 
[xrm.d.ts.zip](https://github.com/delegateas/XrmDefinitelyTyped/files/1633982/xrm.d.ts.zip)

**Comment by skovlund** [comment]
Please take a look at issue #41, which should answer both your questions. Documentation is unfortunately still missing as noted in issue #42.

**Comment by gashupl** [comment]
Ok. Many thanks for clarifications. Waiting for documentation update.
