### ISSUE TITLE
Type Save getting of an Attribute

### ISSUE THREAD

**Issue by jonathandhaene** [delegateas/XrmDefinitelyTyped#54]
How can this

```
_form = <Form.gb_request.Main.Informatie>executionContext.getFormContext();

const invalidLotCount = _form.getAttribute("gb_invalidlotscount");
```

Become
```
_form = <Form.gb_request.Main.Informatie>executionContext.getFormContext();

const invalidLotCount = _form.getAttribute(gb_request.gb_invalidlotscount);
```

**Comment by henrikhannemose** [comment]
Can you elaborate? You first suggestion (`_form.getAttribute("gb_invalidlotscount")`) is the correct one to use. 

With XrmDefinitelyTyped we ensure that you can only type valid strings, i.e. `_form.getAttribute("gb_fieldnotonform")` will give an error.

**Comment by henrikhannemose** [comment]
I am closing this issue. Feel free to re-open it if your issue was not resolved.
