### ISSUE TITLE
Setting ownerid using XrmQuery

### ISSUE THREAD

**Issue by henrikhannemose** [delegateas/XrmDefinitelyTyped#65]
Currently we generate `ownerid_bind$owners` for setting the owner on records using XrmQuery. This results in sending `ownerid@odata.bind : "/owners(<guid>)"` to CRM, which does not work. The expected format can be seen in [Associate entities on create](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/webapi/create-entity-web-api#associate-entities-on-create).

Instead we should generate two different ways of setting ownerid:

- `ownerid_bind$teams`, which should send `ownerid@odata.bind : "/teams(<guid>)"` to CRM.
- `ownerid_bind$systemusers`, which should send `ownerid@odata.bind : "/systemusers(<guid>)"` to CRM.

I have not looked into whether this would have an impact on retrieving ownerid from CRM using XrmQuery.

**Comment by magesoe** [comment]
Added in version 4.3.6
