### ISSUE TITLE
getFormContext() support?

### ISSUE THREAD

**Issue by piyushpaliwal** [delegateas/XrmDefinitelyTyped#66]
Xrm.Page is now deprecated as we know it, just want to check if this supports the [getFormContext()](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/clientapi/clientapi-form-context) yet?

**Comment by TomMalow** [comment]
XrmDefinitelyTyped does support `getFormContext()` and have done for a while. We have written about it in our [wiki](https://github.com/delegateas/XrmDefinitelyTyped/wiki/Form-scripting).
