### ISSUE TITLE
Form intersects not generated anymore

### ISSUE THREAD

**Issue by zaha** [delegateas/XrmDefinitelyTyped#68]
Hi everyone,

I updated to v3.0 and regenerated my entities. Upon fixing all issues with the breaking EntityReferene change I noticed that the compiler is complaining about the intersect forms:

`Namespace 'Form' has no exported member '_special'.`

I checked the typings and could not find the intersect forms anywhere. I regenerated it twice to make sure it wasn't a hiccup. I also checked that the form IDs are still valid.

**Comment by Tolini** [comment]
Thank you for let us know.
I have fixed this in 30a24ca33a498a21b05e4bb3e1a63ca1582aa934 and it will be a part of the next nuget update.

**Comment by zaha** [comment]
Woah, that was quick. Works again, thanks a lot! :)
