### ISSUE TITLE
Extend XrmQuery to implement Query Functions

### ISSUE THREAD

**Issue by TomMalow** [delegateas/XrmDefinitelyTyped#79]
Dynamics 365 9.0 have introduced [Query Functions](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/queryfunctions?view=dynamics-ce-odata-9) that extends the Web API with functions to help create more complex queries. These function are equal to some of the operators found in view filters. 

The new queries implements functions such as `In` and `NotIn` which previously required multiple calls. Other functions were possible but could reduce the size of the filter. Such as:
-`EqualBusinessId`
-`EqualUserId`
-`Today` (date)
-`On` (date)
-`NextXDays` (date)
-`InFiscalYear` (date)
-`Under` (hierarchy)
-`Above` (hierarchy)

An example of how the `In` functions is emplemented the following way:
```
?$filter=Microsoft.Dynamics.CRM.In(PropertyName='atttributeName',PropertyValues=['value','value'])
```

Each function needs to be handled separately. I suggest that the function that provides most value to XDT are prioritized first. As mentioned, some of these function can be created already with normal filtering.

**Comment by magesoe** [comment]
I can not get the queries to work. Calling In returns nothing and calling Contains returns an error that fetchxml does not support Contains. Can you test and confirm that it does not work?

**Comment by magesoe** [comment]
Added in version 4.2.0
