### ISSUE TITLE
Synchronous version of the Query.Execute method

### ISSUE THREAD

**Issue by majakubowski** [delegateas/XrmDefinitelyTyped#83]
Sometimes synchronous execution of query is necessary, eg. CustomRule on EnableRule or PopulateQueryCommand on Ribbon. I think that this can't be handled in asynchronous way.

**Comment by magesoe** [comment]
I added a comment directly on the PR https://github.com/delegateas/XrmDefinitelyTyped/pull/85#issuecomment-464610574
