### ISSUE TITLE
UCI: Promise support for Client API's

### ISSUE THREAD

**Issue by mathiasbl** [delegateas/XrmDefinitelyTyped#86]
Some functions in UCI actually return a Promise and not the custom 'then' function.
For example Xrm.Utility.lookupObjects or Xrm.Data.refresh

Currently in XDT these methods will return a typed Then object.
Maybe add the possibility to generate d.ts files specific for UCI?

**Comment by magesoe** [comment]
So it turns out they also return Promises in Web view as well. However, it does not work correctly for all requests. I tried most requests and changed those that worked to promises. I have not tested it in depth, but tested it enough that I wanted to put it out for testing.
Added in version 4.2.0
