### ISSUE TITLE
Option Set and .includeformattedvalues() does not return the 'value' only the formatted value

### ISSUE THREAD

**Issue by obkirneh** [delegateas/XrmDefinitelyTyped#90]
Hi,

When using .includeformattedvalues() on an option set attribute only the formatted value is returned and is returned as the value and not the formatted value.

See this example:

        XrmQuery.retrieve((x) => x.contacts, "6ac2c8bd-d697-e311-9400-0050569600d2")
            .select((x) => [x.preferredcontactmethodcode, x.parentcustomerid_guid])
            .includeFormattedValues()
            .execute((result) => { 
                if (result === null) { return; }
                console.log(`preferredcontactmethodcode...........: ${result.preferredcontactmethodcode}\n` +
                            `preferredcontactmethodcode_formatted.: ${result.preferredcontactmethodcode_formatted}\n` +
                            `parentcustomerid_guid................: ${result.parentcustomerid_guid}\n` +
                            `parentcustomerid_formatted...........: ${result.parentcustomerid_formatted}`);
            });

Return values:

    preferredcontactmethodcode...........: Any
    preferredcontactmethodcode_formatted.: undefined
    parentcustomerid_guid................: a14c69dd-555e-e311-93f8-0050569600d2
    parentcustomerid_formatted...........: Modtagelsen

I would expect `preferredcontactmethodcode` to be **1** and `preferredcontactmethodcode_formatted` to be **Any**

Regards,
Henrik

**Comment by obkirneh** [comment]
Hi,

Will this change to the **reviver** function in **dg.xrmquery.web.ts** do it?

        if ((beginsWith(newName, '_') && endsWith(newName, '_value')) || formatted) {
            if (beginsWith(newName, '_') && endsWith(newName, '_value')) {
                newName = newName.substr(1, newName.length - 7);
            }
            if (formatted)
                newName += FORMATTED_ENDING;
            else if (lookupLogicalName)
                newName += LOOKUP_LOGICALNAME_ENDING;
            else if (lookupNavProperty)
                newName += LOOKUP_NAVIGATIONPROPERTY_ENDING;
            else
                newName += GUID_ENDING;
        }

I added ` || formatted ` and then the check for stripping underscore and _value inside the if:
```
        if ((beginsWith(newName, '_') && endsWith(newName, '_value')) || formatted) {
            if (beginsWith(newName, '_') && endsWith(newName, '_value')) {
                newName = newName.substr(1, newName.length - 7);
            }
```

I tried it with following example:

        XrmQuery.retrieve((x) => x.contacts, "6ac2c8bd-d697-e311-9400-0050569600d2")
            .select((x) => [x.donotemail, x.preferredcontactmethodcode, x.parentcustomerid_guid, x.createdon])
            .includeFormattedValues()
            .execute((result) => {
            if (result === null) { return; }
            console.log(`preferredcontactmethodcode ${result.preferredcontactmethodcode}\n` +
                        `preferredcontactmethodcode_formatted ${result.preferredcontactmethodcode_formatted}\n` +
                        `parentcustomerid_guid ${result.parentcustomerid_guid}\n` +
                        `parentcustomerid_formatted ${result.parentcustomerid_formatted}\n` +
                        `createdon ${result.createdon}\n` +
                        `createdon_formatted ${result.createdon_formatted}\n` +
                        `donotemail ${result.donotemail}\n` +
                        `donotemail_formatted ${result.donotemail_formatted}`);
            });

and here is the output:

```
preferredcontactmethodcode 1
preferredcontactmethodcode_formatted Any
parentcustomerid_guid a14c69dd-555e-e311-93f8-0050569600d2
parentcustomerid_formatted Modtagelsen
createdon Mon Feb 17 2014 14:23:52 GMT+0100 (Central European Standard Time)
createdon_formatted 17-02-2014 14:23
donotemail false
donotemail_formatted Allow
```

/Henrik

**Comment by TomMalow** [comment]
Hi @obkirneh - Sorry for not responding to you on this issue.

I believe the newest version of XDT, 4.3.13 should have resolved this issue. Can you verify, if it is resolved?

**Comment by obkirneh** [comment]
Hi @TomMalow,

Thanks for the update.

I've updated our sandbox environment to 4.3.13 and now both values are returned.
Here is result from my sample above:

> preferredcontactmethodcode 1
preferredcontactmethodcode_formatted Any
parentcustomerid_guid a14c69dd-555e-e311-93f8-0050569600d2
parentcustomerid_formatted Modtagelsen
createdon Mon Feb 17 2014 14:23:52 GMT+0100 (Central European Standard Time)
createdon_formatted 2/17/2014 2:23 PM
donotemail false
donotemail_formatted Allow

Our code will need review when updating to 4.3.13 becuase now e.q. **preferredcontactmethodcode** has changed from the formatted value to the picklist number.

> Before 4.3.13 : **any**
> In 4.3.13 : **1** 

That is okay with me but important to emphasize in release notes. 

Regards,
Henrik

**Comment by TomMalow** [comment]
Didn't consider the potential breaking changes when fixing this. Good to now. Will look at updating the release notes.

But great to hear that it works.
