### ISSUE TITLE
Xrm.Device.pickFile should return an array

### ISSUE THREAD

**Issue by JonathanWacks** [delegateas/XrmDefinitelyTyped#91]
Xrm.Device.pickFile returns an array of files, according to MSDN - https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/clientapi/reference/xrm-device/pickfile . This is regardless of whether allowMultipleFiles is set to true or false.
Currently, interface Device defines the function as pickFile(pickFileOptions: PickFileOptions): Then< File >;
This should be File[] at the end.

**Comment by magesoe** [comment]
Added in version 4.0.8
