### ISSUE TITLE
Xrm.Page.data.refresh(true);

### ISSUE THREAD

**Issue by plantoschka** [delegateas/XrmDefinitelyTyped#93]
Just updated to 4.2.0 and now all my code has an error where I use Xrm.Page.refresh(). Is this not available anymore?

Xrm.Page.save() is also not available but I found it under Xrm.Page.entity.save()

Should still be available
https://docs.microsoft.com/de-de/dynamics365/customer-engagement/developer/clientapi/reference/formcontext-data/refresh

**Comment by magesoe** [comment]
I might have made a mistake when I tried to turn it into a promise function. Can you show how you try to call it?

**Comment by plantoschka** [comment]
I just define a Page object like
`const Page = <Form.account.Main.Corporate>Xrm.Page`

and then in the function I just did
`Page.data.refresh(true)`

But now in Page.data there is no refresh() or save() method anymore.

**Comment by magesoe** [comment]
Are you using a CRM version older than 9? Because I was able to reproduce your scenario on 8.2, but not on 9.1

**Comment by plantoschka** [comment]
Yes, I am using 8.2

**Comment by magesoe** [comment]
I forgot to add the file I added as an embeddedResource in the project. I tested the fix against 8.2 and it worked for me. The fix was added in version 4.2.1
