### ISSUE TITLE
Error when using XrmQuery.Create and XrmQuery.Update

### ISSUE THREAD

**Issue by GianiNoyez** [delegateas/XrmDefinitelyTyped#94]
```javascript
XrmQuery.create(x => x.accounts, { name: "test"}).execute((id: String) => {})
```
Argument of type '{ name: string; }' is not assignable to parameter of type 'Account_Create'. Type '{ name: string; }' is missing the following properties from type 'Account_Create': displayName, id, rpDisplayNamets(2345)

```javascript
XrmQuery.update((x) => x.accounts, currentid, { name: "test" }).execute((id: string) => {});
```
Gives : Argument of type '{ name: string; }' is not assignable to parameter of type 'Account_Update'. Type '{ name: string; }' is missing the following properties from type 'Account_Update': displayName, id, rpDisplayNamets(2345)

Even when I'm copying examples I get these errors

**Comment by magesoe** [comment]
Add a namespace in the configuration where you specify you want to generate for web

**Comment by magesoe** [comment]
The issue comes from the fact that typescript has a namespace called Account

**Comment by GianiNoyez** [comment]
> Add a namespace in the configuration where you specify you want to generate for web

That is the fix. Thanks a lot for the quick reply.

**Comment by magesoe** [comment]
No problem, thanks for trying out XDT!
