### ISSUE TITLE
Missing Support for Special Unicode Characters like ✓

### ISSUE THREAD

**Issue by krihvi** [delegateas/XrmDefinitelyTyped#96]
Currently if a special characters or symbol is used in a label name we remove it and it becomes an empty string. However a issue might occur when the symbol also contain a mark:
✔️ -> \u2714\ufe0f
The above contain a symbol(✓) and a mark that makes it bold. The symbol is cleaned for not being a word, but the mark will not be removed and stand alone. In this case will XrmDefintelyTyped produce a typing that contains "an illegal character" and show an error. 

A solution is already implemented in XrmContext: Introduce Labelmapping as an additional argument, which replace all occurrence of specified Unicode chars to readable string.
Example: "labelMappings","\u2714\ufe0f: checkmark, \u26D4\ufe0f: stopsign"

**Comment by magesoe** [comment]
Added in 4.3.3
