### ISSUE TITLE
Compile error 

### ISSUE THREAD

**Issue by Niw0n** [delegateas/XrmDefinitelyTyped#99]
Severity	Code	Description	Project	File	Line	Suppression State
Error	TS2312	An interface may only extend a class or another interface.	

core snippet that is generated in xrm.d.ts using latest stable build (4.3.0)

type BaseXrm = typeof Xrm;
/**
 * Client-side xRM object model.
 */
interface Xrm<T extends Xrm.PageBase<Xrm.AttributeCollectionBase, Xrm.TabCollectionBase, Xrm.ControlCollectionBase>> extends BaseXrm {
  /**
   * Various utility functions can be found here.
   */
  Utility: Xrm.Utility;
}

**Comment by magesoe** [comment]
What version of CRM are you using?

**Comment by Niw0n** [comment]
Dynamics 365, v9.0

Skickat från min iPhone

**Comment by magesoe** [comment]
Can you show how you call the exe file, with which settings?

**Comment by Niw0n** [comment]
PARAM
(
	[string] $url = "xxxxx/JOJO/XRMServices/2011/Organization.svc",
	[string] $out = "src\SDS.Crm\Webresources\SDS.Crm.Webresources\typings\XRM",
	[string] $solutions = "SDS",
	[string] $entities = "account, contact",
	[string] $jsLib = "src\SDS.Crm\Webresources\SDS.Crm.Webresources\sds_resources\scripts\library",
	[string] $oneFile = "true",
	[string] $crmVersion = "9.0",
	[string] $username = $(Read-Host "Username"),
	[string] $password = $(Read-Host "Password")
`)

# Define local folder(s)
    [string] $SolutionBaseDirectory = [System.IO.Path]::Combine($PSScriptRoot, "..")
	[string] $OutputDirectory = [System.IO.Path]::Combine($SolutionBaseDirectory, $out)
	[string] $jsLibDirectory = [System.IO.Path]::Combine($SolutionBaseDirectory, $jsLib)

	# Define executable
	[string] $XrmDefinitelyTyped = [System.IO.Path]::Combine($SolutionBaseDirectory, "packages\Delegate.XrmDefinitelyTyped.4.3.0\content\XrmDefinitelyTyped/XrmDefinitelyTyped.exe")
	
	# Validate paths and executables
	if (-Not (Test-Path $XrmDefinitelyTyped -PathType Leaf)) { Throw [System.IO.FileNotFoundException] "Unable to locate XrmDefinitelyTyped executable: $XrmDefinitelyTyped" }
	
	# Execute
	& $XrmDefinitelyTyped -url="$url" -username="$username" -password="$password" -jsLib="$jsLibDirectory" -cv="$crmVersion" -solutions="$solutions" -entities="$entities" -out="$OutputDirectory" -of="$oneFile" -web

**Comment by Niw0n** [comment]
It wasn´t a build error, it was an intellisense error. Im terribly sorry for this. everything works perfectly fine.

**Comment by magesoe** [comment]
Good to know, thanks for reaching out anyway!
